"""Export competitor prices as a JavaScript snippet for the React calculators.

Generates a COMP_DATA object that drops directly into the product page
calculator HTML files on priorityprintservice.com.

Usage:
    pps export-comp-js                     # writes comp-data.js
    pps export-comp-js -o my-output.js     # custom path
    pps export-comp-js -p brochures        # one product only
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import click
from rich.console import Console

from pps_tools.storage.queries import get_latest_prices
from pps_tools.utils.config import get_products

console = Console()


def _build_spec_string(product_key: str, products_config: dict) -> str:
    """Build a human-readable spec string from product config."""
    info = products_config.get(product_key, {})
    specs = info.get("default_specs", {})

    parts = []
    if specs.get("size"):
        parts.append(specs["size"])
    if specs.get("paper_type"):
        parts.append(specs["paper_type"].replace("_", " "))
    if specs.get("color_mode"):
        parts.append(specs["color_mode"].replace("_", " "))
    if specs.get("sides"):
        s = specs["sides"]
        parts.append("both sides" if s == "double" else s + "-sided")
    if specs.get("finish") and specs["finish"] != "none":
        parts.append(specs["finish"].replace("_", "-"))

    return ", ".join(parts)


def build_comp_data(points, products_config: dict, round_prices: bool = True) -> dict:
    """Transform a list of PricePoints into the COMP_DATA nested structure.

    Returns:
        {
            "booklets": {
                "spec": "8.5x11, 80lb gloss, full color, both sides, saddle-stitch",
                "tiers": {
                    25: {"gotprint": 32, "overnightprints": 40, ...},
                    50: {...},
                }
            },
            ...
        }
    """
    comp_data: dict = {}

    for point in points:
        product_key = point.product
        qty = point.quantity
        competitor = point.competitor
        price = round(point.total_price) if round_prices else point.total_price

        if product_key not in comp_data:
            spec = _build_spec_string(product_key, products_config)
            comp_data[product_key] = {"spec": spec, "tiers": {}}

        tiers = comp_data[product_key]["tiers"]
        if qty not in tiers:
            tiers[qty] = {}

        # Keep lowest price per competitor/qty (dedup)
        existing = tiers[qty].get(competitor)
        if existing is None or price < existing:
            tiers[qty][competitor] = price

    # Sort tiers by quantity
    for product_key in comp_data:
        comp_data[product_key]["tiers"] = dict(
            sorted(comp_data[product_key]["tiers"].items())
        )

    return comp_data


def render_js(comp_data: dict, var_name: str = "COMP_DATA") -> str:
    """Render the COMP_DATA dict as a JavaScript const declaration."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        f"// Generated by: pps export-comp-js",
        f"// Date: {now}",
        f"// Paste this into your calculator HTML file, replacing the old {var_name} block.",
        "",
    ]

    # Use json.dumps, then strip quotes from integer keys for cleaner JS
    json_str = json.dumps(comp_data, indent=2)

    lines.append(f"const {var_name} = {json_str};")
    return "\n".join(lines)


@click.command("export-comp-js")
@click.option("-o", "--output", "output_path", type=click.Path(),
              default="comp-data.js", help="Output file path")
@click.option("-p", "--product", "products", multiple=True,
              help="Filter to specific products (repeatable)")
@click.option("--var-name", default="COMP_DATA",
              help="JavaScript variable name (default: COMP_DATA)")
@click.option("--round/--no-round", "round_prices", default=True,
              help="Round prices to nearest integer (default: yes)")
def export_comp_js(output_path, products, var_name, round_prices):
    """Export competitor prices as a JavaScript snippet.

    Reads the latest scraped prices from the database and generates
    a JavaScript file containing a COMP_DATA object. Paste this into
    your React calculator HTML file to update competitor prices.
    """
    products_config = get_products()

    # Fetch latest prices, optionally filtered
    all_points = []
    if products:
        for prod in products:
            all_points.extend(get_latest_prices(product=prod))
    else:
        all_points = get_latest_prices()

    if not all_points:
        console.print("[yellow]No competitor pricing data in database.[/yellow]")
        console.print("Run 'pps scrape-all' first to fetch prices.")
        return

    comp_data = build_comp_data(all_points, products_config, round_prices)
    js_output = render_js(comp_data, var_name)

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(js_output)

    # Summary
    total_products = len(comp_data)
    total_competitors = len({
        c for p in comp_data.values() for t in p["tiers"].values() for c in t
    })
    total_tiers = sum(len(p["tiers"]) for p in comp_data.values())

    console.print(f"[green]Exported to: {path}[/green]")
    console.print(
        f"  {total_products} products, {total_competitors} competitors, "
        f"{total_tiers} quantity tiers"
    )
    console.print(f"\n  Paste the contents of [cyan]{path}[/cyan] into your calculator HTML file.")
