// ---------- interior combat demonstration: free placement ----------
// The building is generated by the interiors generator (tools/interiors, its own topic) and drawn by its renderer.
// This page adds the fight. Nobody stands on a grid: units move to any point in reach (a glowing outline), clicks near
// cover snap behind it, sight is drawn as fans cut by walls, and cover is whatever really stands between a unit and the
// shooter. Four roles (Ranger, Sharpshooter, Breacher, Medic), ammo, pipe bombs that destroy cover, first aid,
// bleeding out, and raiders who break and run. Rules: tools/combat/rules.js. Space: tools/combat/space.js.
(()=>{
const CR=CombatRules, $=id=>document.getElementById(id);
const hudEl=$('hud'), hoverEl=$('hover'), logEl=$('log'), bannerEl=$('banner'), unitsEl=$('units'), actsEl=$('acts');
const INKS={selected:0xe0a526,calm:0x1d1814,overwatch:0x2f9fc4,concealed:0x5b6fa8,wounded:0xc23b2e,panicked:0x9b4fc4,raider:0x6e1a10,dead:0x77726a};
const SQUAD=[['Rosa','ranger'],['Dev','sharpshooter'],['Malik','breacher'],['June','medic']];
view.marks=false; view.mode='cutaway'; view.el=.95; view.dist=22;
renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));
scene.add(new THREE.AmbientLight(0xffffff,.18));

// ---------- state ----------
const S={timeScale:1,w:null,G:null,rec:null,units:[],sel:null,phase:'explore',turn:'squad',mode:'move',busy:false,round:1,minutes:14*60,seed:0,F:null,camGoal:null,sight:true,free:false,destroyed:new Set(),stats:null};
let dirtyBuild=false, shake=0;
const order=SITES.map((s,i)=>i).sort((a,b)=>(SITES[b].id==='newriver/2_2/0')-(SITES[a].id==='newriver/2_2/0'));
for(const i of order){ const s=SITES[i]; const o=document.createElement('option'); o.value=i; o.textContent=(s.name||(s.house?'House':'Building'))+' · '+s.id; $('bSel').appendChild(o); }
const P=u=>[u.x,u.z];
const yOf=(x,z)=>S.w.floorY(x,z);
const roleOf=u=>CR.ROLES[u.role];

// ---------- overlays ----------
// reach: a faint tint over everything in range, and a glowing band along the edge of one action (blue) and a dash (gold)
const fillG=new THREE.PlaneGeometry(.52,.52); fillG.rotateX(-Math.PI/2);
const fill=new THREE.InstancedMesh(fillG,new THREE.MeshBasicMaterial({transparent:true,opacity:.07,depthWrite:false}),20000); fill.instanceColor=new THREE.InstancedBufferAttribute(new Float32Array(20000*3),3); fill.count=0; fill.frustumCulled=false; fill.renderOrder=4; scene.add(fill);
// the band: a bright core line with a soft halo either side that breathes slowly
const glowMats=[];
function glowMat(color){ const m=new THREE.ShaderMaterial({uniforms:{c:{value:new THREE.Color(color)},t:{value:0}},transparent:true,depthWrite:false,side:THREE.DoubleSide,
  vertexShader:'attribute float side; varying float vS; void main(){ vS=side; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0); }',
  fragmentShader:'uniform vec3 c; uniform float t; varying float vS; void main(){ float k=1.0-abs(vS); float core=smoothstep(0.78,0.97,k); float halo=pow(k,1.7)*(0.72+0.2*sin(t*2.6)); vec3 col=mix(c,vec3(1.0),core*0.6); gl_FragColor=vec4(col,clamp(max(core,halo),0.0,1.0)); }'});
  glowMats.push(m); return m; }
const ribbonM={near:glowMat(0x4aa3ff),far:glowMat(0xffb42e),blast:glowMat(0xff5a3a)};
const ribbons=new THREE.Group(); scene.add(ribbons);
const tmpM=new THREE.Matrix4(), col=new THREE.Color();
function clearReach(){ fill.count=0; while(ribbons.children.length){ ribbons.children.pop().geometry.dispose(); } }
// marching squares over the hidden cost field: the outline where the cost crosses a budget
function contour(F,T){ const w=S.w, NW=w.NW, NH=w.NH, out=[]; const v=n=>isFinite(F.cost[n])?F.cost[n]:T+3;
  const lerp=(ax,az,av,bx,bz,bv)=>{ const t=(T-av)/(bv-av); return [ax+(bx-ax)*t,az+(bz-az)*t]; };
  for(let j=0;j<NH-1;j++) for(let i=0;i<NW-1;i++){ const a=j*NW+i, b=a+1, c=a+NW+1, d=a+NW, va=v(a), vb=v(b), vc=v(c), vd=v(d);
    const k=(va<=T?1:0)|(vb<=T?2:0)|(vc<=T?4:0)|(vd<=T?8:0); if(k===0||k===15) continue;
    const ax=w.nodeX(a), az=w.nodeZ(a), bx=w.nodeX(b), bz=w.nodeZ(b), cx=w.nodeX(c), cz=w.nodeZ(c), dx=w.nodeX(d), dz=w.nodeZ(d);
    const AB=()=>lerp(ax,az,va,bx,bz,vb), BC=()=>lerp(bx,bz,vb,cx,cz,vc), CD=()=>lerp(cx,cz,vc,dx,dz,vd), DA=()=>lerp(dx,dz,vd,ax,az,va);
    const segs={1:[[DA,AB]],2:[[AB,BC]],3:[[DA,BC]],4:[[BC,CD]],5:[[DA,AB],[BC,CD]],6:[[AB,CD]],7:[[DA,CD]],8:[[CD,DA]],9:[[CD,AB]],10:[[AB,BC],[CD,DA]],11:[[CD,BC]],12:[[BC,DA]],13:[[BC,AB]],14:[[AB,DA]]}[k];
    for(const [p,q] of segs) out.push([p(),q()]); }
  return out; }
function ribbonMesh(segs,mat,W){ W=W||.3; const pos=[], side=[]; for(const [a,b] of segs){ const dx=b[0]-a[0], dz=b[1]-a[1], L=Math.hypot(dx,dz)||1, nx=-dz/L*W, nz=dx/L*W, ya=yOf(a[0],a[1])+.05, yb=yOf(b[0],b[1])+.05;
    pos.push(a[0]+nx,ya,a[1]+nz, b[0]+nx,yb,b[1]+nz, b[0]-nx,yb,b[1]-nz, a[0]+nx,ya,a[1]+nz, b[0]-nx,yb,b[1]-nz, a[0]-nx,ya,a[1]-nz); side.push(1,1,-1,1,-1,-1); }
  const g=new THREE.BufferGeometry(); g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3)); g.setAttribute('side',new THREE.Float32BufferAttribute(side,1)); const m=new THREE.Mesh(g,mat); m.renderOrder=5; m.frustumCulled=false; return m; }
function ring(c,r){ const segs=[], n=48; for(let k=0;k<n;k++){ const a=k/n*Math.PI*2, b=(k+1)/n*Math.PI*2; segs.push([[c[0]+Math.sin(a)*r,c[1]+Math.cos(a)*r],[c[0]+Math.sin(b)*r,c[1]+Math.cos(b)*r]]); } return segs; }
function drawReach(){ clearReach(); const u=S.sel; S.F=null; if(!u||!u.alive||u.team!=='squad'||S.busy||S.turn!=='squad'||S.phase==='over'||S.phase==='breach'||S.mode!=='move') return; const b=budget(u); if(!b) return;
  S.F=S.w.field(P(u),b,others(u)); const F=S.F;
  for(let n=0;n<F.cost.length;n++){ const c=F.cost[n]; if(!(c<=b)||fill.count>=20000) continue; tmpM.makeTranslation(S.w.nodeX(n),yOf(S.w.nodeX(n),S.w.nodeZ(n))+.03,S.w.nodeZ(n)); fill.setMatrixAt(fill.count,tmpM); fill.setColorAt(fill.count,col.setHex(c<=CR.V.move||S.phase==='explore'?0x3f8fd1:0xe0a526)); fill.count++; }
  fill.instanceMatrix.needsUpdate=true; fill.instanceColor.needsUpdate=true;
  if(S.phase==='explore') ribbons.add(ribbonMesh(contour(F,b),ribbonM.near));
  else { if(b>CR.V.move) ribbons.add(ribbonMesh(contour(F,b),ribbonM.far)); ribbons.add(ribbonMesh(contour(F,CR.V.move),ribbonM.near)); } }
// sight: fans cut where walls and tall things stop the eye
const fans=new THREE.Group(); scene.add(fans);
const fanM={raider:new THREE.MeshBasicMaterial({color:0xc23b2e,transparent:true,opacity:.2,depthWrite:false,side:THREE.DoubleSide}),own:new THREE.MeshBasicMaterial({color:0x3fae7f,transparent:true,opacity:.14,depthWrite:false,side:THREE.DoubleSide})};
function fan(x,z,a0,a1,maxD,mat){ const pos=[], n=Math.max(8,Math.ceil((a1-a0)/(Math.PI/120))), y=yOf(x,z)+.06; let prev=null;
  for(let k=0;k<=n;k++){ const a=a0+(a1-a0)*k/n, d=S.w.castRay([x,z],a,maxD), p=[x+Math.sin(a)*d,z+Math.cos(a)*d]; if(prev) pos.push(x,y,z, prev[0],y,prev[1], p[0],y,p[1]); prev=p; }
  const g=new THREE.BufferGeometry(); g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3)); const m=new THREE.Mesh(g,mat); m.renderOrder=3; return m; }
function drawSight(){ while(fans.children.length){ fans.children.pop().geometry.dispose(); } if(!S.sight||!S.w) return;
  if(S.phase==='explore'){ for(const r of S.units) if(r.team==='raider'&&r.alive&&r.unaware){ fans.add(fan(r.x,r.z,r.face-CR.V.cone,r.face+CR.V.cone,CR.V.sight,fanM.raider)); fans.add(fan(r.x,r.z,0,Math.PI*2,CR.V.around,fanM.raider)); } }
  else if(S.phase==='combat'&&S.sel&&S.sel.alive&&S.sel.team==='squad') fans.add(fan(S.sel.x,S.sel.z,0,Math.PI*2,CR.V.spot,fanM.own)); }
// the hovered spot: a ring where the unit would stand, the route there, and a marker toward each foe for the cover it would have
const ringG=new THREE.RingGeometry(.3,.4,28); ringG.rotateX(-Math.PI/2);
const ghost=new THREE.Mesh(ringG,new THREE.MeshBasicMaterial({color:0xf3d38a,transparent:true,opacity:.9,depthWrite:false})); ghost.renderOrder=6; ghost.visible=false; scene.add(ghost);
const route=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:0xf3d38a,dashSize:.25,gapSize:.15})); route.visible=false; scene.add(route);
const glyphs=new THREE.Group(); scene.add(glyphs);
const glyphG=new THREE.BoxGeometry(1,1,1), glyphM={2:new THREE.MeshBasicMaterial({color:0xe0a526}),1:new THREE.MeshBasicMaterial({color:0xe0a526,transparent:true,opacity:.6}),0:new THREE.MeshBasicMaterial({color:0xc23b2e})};
const entryMarks=new THREE.Group(); scene.add(entryMarks);
function drawEntries(){ while(entryMarks.children.length) entryMarks.children.pop(); if(S.phase!=='explore') return;
  for(const e of S.w.entries()){ const ok=usable(e,S.sel), blocked=!S.w.props(e.o).cross; if(!ok&&!blocked) continue;
    const m=new THREE.Mesh(ringG,new THREE.MeshBasicMaterial({color:blocked?(ok?0xff7a4a:0x6c6a66):e.kind==='window'?0x9fd3e6:0xe0a526,transparent:true,opacity:blocked&&!ok?.45:.75,depthWrite:false})); m.scale.setScalar(.8); m.position.set(e.out[0],.05,e.out[1]); m.renderOrder=6; entryMarks.add(m); } }
const aimLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineDashedMaterial({color:0xe0a526,dashSize:.3,gapSize:.2})); aimLine.visible=false; scene.add(aimLine);
function showAim(a,b){ if(!a||!b){ aimLine.visible=false; return; } const lf=CR.lineOfFire(S.w,a,b)||{from:P(a),to:P(b)}; const p=aimLine.geometry.attributes.position;
  p.setXYZ(0,lf.from[0],yOf(...lf.from)+1.35,lf.from[1]); p.setXYZ(1,lf.to[0],yOf(...lf.to)+1.25,lf.to[1]); p.needsUpdate=true; aimLine.computeLineDistances(); aimLine.visible=true; }
// a throw: the arc while aiming, and the blast circle where it lands
const arc=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:0xff7a4a,dashSize:.25,gapSize:.15})); arc.visible=false; scene.add(arc);
function arcPoints(a,b,n){ const pts=[], y0=yOf(...a)+1.5, y1=yOf(...b)+.1, L=Math.hypot(b[0]-a[0],b[1]-a[1]); for(let k=0;k<=n;k++){ const t=k/n; pts.push(new THREE.Vector3(a[0]+(b[0]-a[0])*t,y0+(y1-y0)*t+Math.sin(t*Math.PI)*Math.max(1.2,L*.28),a[1]+(b[1]-a[1])*t)); } return pts; }
const blastFx=[];

// ---------- figures ----------
const gunG={long:new THREE.BoxGeometry(.05,.9,.07),mid:new THREE.BoxGeometry(.055,.62,.08),short:new THREE.BoxGeometry(.07,.58,.09)}; for(const k in gunG) gunG[k].translate(0,-.3,.02);
const gunM=new THREE.MeshLambertMaterial({color:0x2b2a28});
function makeFig(seed,fem,ink,profile){ const f=FigureKit.figure(fem,FigureKit.genFace(seed,fem)); f.ink=FigureKit.inkUp(f.root,{persp:true,width:.0016,color:ink}); const g=new THREE.Mesh(gunG[profile||'mid'],gunM); g.position.set(0,-.24,0); f.el[0].add(g); scene.add(f.root); return f; }
function ink(u){ if(!u.fig) return; const k=u.dead?'dead':u.down?'wounded':!u.alive?'dead':u.team==='raider'?(u.fleeing?'panicked':'raider'):S.phase==='explore'?(S.sel===u?'selected':'concealed'):u.ow?'overwatch':u.hp<=u.max/2?'wounded':S.sel===u?'selected':'calm'; u.fig.ink.color.setHex(INKS[k]); }
const inkAll=()=>S.units.forEach(ink);

// ---------- popups, tracers, log ----------
const pops=[], tracers=[], waits=[];
const wait=ms=>new Promise(r=>waits.push({t:ms,r}));
function pop(u,text,cls){ const el=document.createElement('div'); el.className='pop '+(cls||''); el.textContent=text; $('stage').appendChild(el); pops.push({el,x:u.x!=null?u.x:u[0],y:(u.x!=null?yOf(u.x,u.z):yOf(u[0],u[1]))+2.2,z:u.z!=null?u.z:u[1],t:0}); }
function tracer(a,b,hit,r){ const off=hit?0:(r()-.5)*1.6; const g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(a[0],yOf(...a)+1.35,a[1]),new THREE.Vector3(b[0]+off,yOf(...b)+(hit?1.2:1.7),b[1]-off)]);
  const l=new THREE.Line(g,new THREE.LineBasicMaterial({color:0xffe3a0,transparent:true})); scene.add(l); tracers.push({l,t:0}); }
function log(t){ const p=document.createElement('p'); p.textContent=t; logEl.prepend(p); while(logEl.children.length>50) logEl.lastChild.remove(); }
function flash(title,text,ours,keep){ bannerEl.className='banner'+(ours?' ours':''); bannerEl.innerHTML=`<b>${title}</b>${text}`; bannerEl.hidden=false; clearTimeout(flash.t); if(!keep) flash.t=setTimeout(()=>bannerEl.hidden=true,3800); }
const clock=()=>{ const m=S.minutes%(24*60); return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0'); };

// ---------- setting up a fight ----------
function setup(){
  const site=SITES[+$('bSel').value], hist=$('hSel').value, seedStr=site.id+(S.seed?'#'+S.seed:'');
  for(const u of S.units) if(u.fig) scene.remove(u.fig.root);
  const G=generate(site,'auto',seedStr,hist); const w=InteriorSpace.fromGenerated(G);
  Object.assign(S,{G,w,rec:{doors:w.doorSt,taken:[]},units:[],phase:'explore',turn:'squad',round:1,minutes:14*60,busy:false,free:false,mode:'move',rng:CR.rng(seedStr+'|fight'),destroyed:new Set(),stats:{shots:0,hits:0,bombs:0}});
  logEl.innerHTML=''; bannerEl.hidden=true;
  rebuild();
  // the generator's people, with roles: a sentry looks out of a street-side window
  const ppl=w.posted(seedStr);
  ppl.forEach((p,i)=>{ const u=CR.makeUnit(p.boss?'boss':'raider',{id:'r'+i,team:'raider',boss:p.boss,name:p.boss?(p.side==='raider'?'Raider boss':'Holdout leader'):p.role==='sentry'?'Sentry':(p.side==='raider'?'Raider':'Holdout'),x:p.p[0],z:p.p[1],ap:0,unaware:true,face:p.face,post:p.role,look:p.face,lookT:0});
    u.fig=makeFig(4000+i*13+S.seed*7,i%2===1,INKS.raider,u.weapon.profile); S.units.push(u); });
  // the squad gathers outside the front door, as close as it can without standing in anyone's sight
  const fa=w.frontApproach(); const start=fa?fa.out:[w.X0+14,w.Z0+14]; const nrm=fa?[fa.out[0]-fa.in[0],fa.out[1]-fa.in[1]]:[0,1], L=Math.hypot(...nrm); const n=[nrm[0]/L,nrm[1]/L], t=[-n[1],n[0]];
  const spots=[]; const ok=q=>w.clearAt(q[0],q[1],w.R+.1)&&!w.insideAt(q[0],q[1])&&!spots.some(s=>Math.hypot(s[0]-q[0],s[1]-q[1])<1.1)&&!S.units.some(r=>CR.sees(w,r,q));
  for(let d=6;d<30&&spots.length<4;d+=.5) for(const s of [0,1.2,-1.2,2.4,-2.4,3.6,-3.6]){ const q=[start[0]+n[0]*d+t[0]*s,start[1]+n[1]*d+t[1]*s]; if(spots.length<4&&ok(q)) spots.push(q); }
  for(let d=6;spots.length<4&&d<30;d+=.5) for(let a=0;a<12&&spots.length<4;a++){ const q=[start[0]+Math.sin(a)*d,start[1]+Math.cos(a)*d]; if(w.clearAt(q[0],q[1],w.R+.1)&&!w.insideAt(...q)&&!spots.some(s=>Math.hypot(s[0]-q[0],s[1]-q[1])<1.1)) spots.push(q); }
  spots.forEach((q,i)=>{ const [name,role]=SQUAD[i]; const u=CR.makeUnit(role,{id:'s'+i,team:'squad',name,x:q[0],z:q[1],face:Math.atan2(-n[0],-n[1])}); u.fig=makeFig(900+i*31+S.seed*3,i%2===0,INKS.concealed,u.weapon.profile); S.units.push(u); });
  S.sel=S.units.find(u=>u.team==='squad'); view.target.set(S.sel.x,0,S.sel.z); view.az=Math.atan2(n[0],n[1]);
  inkAll(); select(S.sel); drawHud(); drawEntries();
  log(`${G.label}, ${hist==='den'?'raider den':'holdout'}: ${ppl.length} inside. Generated in ${G.ms|0} ms.`);
  flash('Concealed','Nobody inside has seen you. Red fans are their eyes. Move anywhere inside the glowing outline; click near cover to tuck in behind it. Gold rings mark doors, blue rings windows, orange ones are barricaded (Malik can blow them). Stand on one to stack, then breach.',true);
}
// the interiors renderer draws the building; its people are ours to draw, and furniture we blew apart is drawn as rubble
function rebuild(){ const items=S.destroyed.size?S.G.Fn.items.map(it=>S.destroyed.has(it.id)?Object.assign({},it,{spec:IT.debris}):it):S.G.Fn.items;
  build(Object.assign({},S.G,{D:{people:[]},Fn:Object.assign({},S.G.Fn,{items})}),S.rec); dirtyBuild=false;
  // hide the renderer's gold door-to-2 m-grid markers: a debug aid for the interiors page, noise in a fight
  world.traverse(o=>{ if(o.isMesh&&o.material&&o.material.isMeshBasicMaterial&&o.material.vertexColors&&o.material.transparent&&o.material.opacity===.55) o.visible=false; }); }

// ---------- selection, reach, the action bar ----------
const others=except=>S.units.filter(u=>u.alive&&u!==except).map(P).concat(S.units.filter(u=>u.down&&!u.dead).map(P));
function select(u){ if(!u||!u.alive) return; S.sel=u; S.mode='move'; arc.visible=false; inkAll(); S.camGoal={x:u.x,z:u.z}; drawReach(); drawSight(); drawBar(); if(S.phase==='explore') drawEntries(); }
function budget(u){ return S.phase==='explore'?2*CR.V.move:(u.ap>=2?2*CR.V.move:u.ap===1?CR.V.move:0); }
const foes=u=>S.units.filter(t=>t.alive&&t.team!==u.team);
const squad=()=>S.units.filter(u=>u.team==='squad');
// an entry is usable when the body can go through it, or when it is barricaded/boarded and a Breacher with a charge stacks there
function usable(e,u){ if(!S.w.clearAt(e.out[0],e.out[1])) return false; if(S.w.props(e.o).cross&&e.kind!=='garage') return true; return !!(u&&u.role==='breacher'&&u.kit.charge>0&&(e.kind!=='garage')); }
const entryAt=u=>S.w.entries().find(e=>Math.hypot(e.out[0]-u.x,e.out[1]-u.z)<1.1&&usable(e,u)&&!squad().some(v=>v!==u&&v.stack===e));
function openDoorBeside(u){ for(const o of S.w.obs) if(o.kind==='edge'&&o.e.type==='door'&&S.w.doorState(o.e)==='open'){ const m=[(o.seg[0]+o.seg[2])/2,(o.seg[1]+o.seg[3])/2]; if(Math.hypot(m[0]-u.x,m[1]-u.z)<1.4) return o; } return null; }
const aidTargets=u=>squad().filter(v=>!v.dead&&(v===u?v.hp<v.max&&v.alive:Math.hypot(v.x-u.x,v.z-u.z)<1.8&&(v.down||v.hp<v.max)));
function unitLabel(v){ if(v.dead) return 'dead'; if(v.down) return v.stable?'down · stable':`bleeding · ${v.bleed}`; return S.phase==='explore'?(v.stack?'stacked':'ready'):'●'.repeat(Math.min(v.ap,3))+'○'.repeat(Math.max(0,2-v.ap)); }
function drawBar(){ const u=S.sel;
  unitsEl.innerHTML=S.units.map((v,i)=>v.team==='squad'?`<button type="button" class="unit${v.dead?' dead':v.down?' down':''}" data-i="${i}" aria-pressed="${S.sel===v}" ${v.alive?'':'disabled'}>${v.name} <em>${roleOf(v).label}</em><br>${unitLabel(v)} · ${v.ammo}/${v.weapon.ammo}${v.ow?' · OW':''}${v.hunker?' · HNK':''}${v.free?' · free':''}<i><s style="width:${v.hp/v.max*100}%;background:${v.hp<=v.max/2?'#c23b2e':'#3fae7f'}"></s></i></button>`
    :`<span class="unit foe${v.alive?'':' dead'}${v.fleeing&&v.alive?' flee':''}">${v.name}${v.fled?' · fled':!v.alive?' · down':v.fleeing?' · running':v.unaware?' · unaware':''}<i><s style="width:${v.hp/v.max*100}%;background:#c23b2e"></s></i></span>`).join('');
  if(S.phase==='over'){ actsEl.innerHTML='<button type="button" class="pri" data-a="restart">Again</button><button type="button" data-a="reroll">Another layout</button>'; return; }
  if(S.turn!=='squad'||S.phase==='breach'){ actsEl.innerHTML=`<span class="hint" style="color:#e2b0a8">${S.phase==='breach'?'Breaching…':'Raiders\' turn…'}</span>`; return; }
  const mine=!S.busy&&u&&u.alive&&u.team==='squad';
  if(S.mode==='shoot'&&mine){ const ts=foes(u).filter(t=>CR.dist(u,t)<45&&CR.lineOfFire(S.w,u,t));
    actsEl.innerHTML=(ts.length?ts.map(t=>{ const o=shotOdds(u,t); return `<button type="button" class="pri" data-t="${S.units.indexOf(t)}">${t.name}: ${o.aim}%${o.flanked?' · flanked':o.cover===2?' · full cover':' · half cover'}</button>`; }).join(''):'<span class="hint">No line of fire from here</span>')+'<button type="button" data-a="back">Back</button>'; return; }
  if(S.mode==='throw'&&mine){ actsEl.innerHTML=`<span class="hint">Click where the pipe bomb lands (${CR.V.throwRange} m, ${CR.V.blastRadius} m blast)</span><button type="button" data-a="back">Back</button>`; return; }
  if(S.mode==='aid'&&mine){ actsEl.innerHTML=aidTargets(u).map(v=>`<button type="button" class="pri" data-aid="${S.units.indexOf(v)}">${v===u?'Self':v.name}: ${v.down?(v.stable?'get up (2 HP)':'stabilise'):'+'+CR.V.aidHeal+' HP'}</button>`).join('')+'<button type="button" data-a="back">Back</button>'; return; }
  if(S.phase==='explore'){ const e=mine&&(u.stack||entryAt(u)), stacked=squad().filter(v=>v.alive&&v.stack), anyLine=mine&&squad().some(v=>v.alive&&S.units.some(t=>t.team==='raider'&&t.alive&&CR.dist(v,t)<CR.V.spot&&CR.lineOfFire(S.w,v,t)));
    const blown=e&&!S.w.props(e.o).cross;
    actsEl.innerHTML=(e?`<button type="button" data-a="stack" aria-pressed="${!!u.stack}">${u.stack?'Unstack':(blown?'Set charge on ':'Stack at ')+(e.kind==='window'?'window':e.role==='front'?'front door':e.role==='back'?'back door':'side door')}</button>`:'')+
      `<button type="button" class="pri" data-a="breach" ${stacked.length&&!S.busy?'':'disabled'}>Breach${stacked.length?' ('+stacked.length+')':''} [B]</button><button type="button" data-a="fire" ${anyLine?'':'disabled'}>Open fire</button><button type="button" data-a="wait" ${S.busy?'disabled':''}>Wait [⌫]</button>`; return; }
  const can=mine&&u.ap>0, od=can&&openDoorBeside(u);
  const extra=[];
  if(u&&u.role==='breacher') extra.push(`<button type="button" data-a="throw" ${can&&u.kit.pipe>0?'':'disabled'}>Pipe bomb ×${u.kit.pipe} [5]</button>`);
  if(u&&u.role==='medic') extra.push(`<button type="button" data-a="aid" ${can&&u.kit.aid>0&&aidTargets(u).length?'':'disabled'}>First aid ×${u.kit.aid} [5]</button>`);
  if(u&&u.role==='ranger') extra.push(`<button type="button" data-a="rungun" ${mine&&!u.cooldown&&u.ap<3?'':'disabled'} title="${roleOf(u).skill}">Run and gun${u.cooldown?' ('+u.cooldown+')':''} [5]</button>`);
  actsEl.innerHTML=`<button type="button" data-a="shoot" class="pri" ${mine&&(u.ap>0||u.free)&&u.ammo>0?'':'disabled'}>${u&&u.ammo<=0?'Empty':u&&u.free?'Free shot':'Shoot'} [1]</button><button type="button" data-a="ow" ${can&&u.ammo>0?'':'disabled'}>Overwatch [2]</button><button type="button" data-a="hunker" ${can?'':'disabled'}>Hunker [3]</button><button type="button" data-a="reload" ${can&&u.ammo<u.weapon.ammo?'':'disabled'}>Reload [4]</button>${extra.join('')}${od?'<button type="button" data-a="close">Close door</button>':''}<button type="button" data-a="end" ${S.busy?'disabled':''}>${S.free?'Skip free shots':'End turn'} [⌫]</button>`; }
function drawHud(){ const left=S.units.filter(u=>u.team==='raider'&&u.alive).length;
  hudEl.innerHTML=`<b>${S.phase==='explore'?'Concealed':S.phase==='over'?'Over':S.phase==='breach'?'Breach':S.turn==='squad'?'Your turn':'Raiders'}</b>${clock()} · ${S.phase==='explore'?'exploring':'round '+S.round} · ${left} inside left<div class="sub">${S.G.label} · ${S.w.G.site.id}</div>`+
    (S.sel&&S.sel.team==='squad'?`<div class="sub">${S.sel.name}: ${S.sel.weapon.name} (${S.sel.weapon.profile} range) · ${roleOf(S.sel).skill}</div>`:''); }
function whyHtml(o){ return '<div class="why">'+o.why.map(([k,v],i)=>`<span>${k}</span><span class="${i===0?'':v<0?'neg':'pos'}">${i===0?v:(v>0?'+':'')+v}</span>`).join('')+`<b>Hit</b><b>${o.aim}%</b><span>Crit</span><span>${o.crit}%</span></div>`; }
const shotOdds=(u,t,extra)=>CR.odds(S.w,u,t,Object.assign({free:u.free,mod:u.entryMod||0,modLabel:'Through a window',steady:u.role==='sharpshooter'&&u.ap>=2&&!u.free},extra||{}));

// ---------- doing things ----------
// walk a route point by point; doors open and glass breaks as the walker reaches them; overwatch can interrupt
function walk(u,points){ return new Promise(res=>{ u.route=points.slice(1).map(q=>({x:q.x,z:q.z,through:q.through})); u.done=res; u.trav=0; }); }
function opening(u,o){ const e=o.e;
  if(/door/.test(e.type)&&S.w.doorState(e)==='closed'){ S.w.setDoor(e.key,'open'); dirtyBuild=true; noise(u,4,'door'); }
  if(e.type==='window'&&e.win.state==='intact'){ S.w.setWindow(e.key,'broken'); dirtyBuild=true; noise(u,14,'glass'); pop(u,'glass','info'); } }
// noise: unaware raiders within earshot turn to face it (walls halve the range)
function noise(u,radius,what){ if(S.phase!=='explore') return; const at=u.x!=null?P(u):u; for(const r of S.units) if(r.team==='raider'&&r.alive&&r.unaware){ const d=Math.hypot(r.x-at[0],r.z-at[1]), heard=S.w.sight(P(r),at)?radius:radius/2; if(d<=heard){ r.look=Math.atan2(at[0]-r.x,at[1]-r.z); r.lookT=6; log(`${r.name} heard the ${what}.`); } } }
async function moveTo(u,p){ const F=S.F; if(!F) return false; const path=S.w.pathTo(F,p); if(!path) return false;
  S.busy=true; clearReach(); hideHover(); drawBar(); const ph=S.phase;
  if(S.phase==='combat'){ u.ap-=path.cost<=CR.V.move?1:2; u.ap=Math.max(0,u.ap); u.ow=false; u.hunker=false; u.moved=true; }
  u.stack=null; await walk(u,path.points);
  if(S.phase!==ph) return true;   // spotted on the way: the fight has already started
  S.busy=false; if(dirtyBuild) rebuild();
  if(S.phase==='explore'&&!spottedCheck()){ raidersLook(1.2); drawSight(); }
  if(S.phase==='combat'&&!checkEnd()) afterAction(u); else if(S.phase==='explore'){ drawReach(); drawBar(); drawEntries(); }
  return true; }
async function shoot(a,b,opt={}){ const o=opt.odds||CR.odds(S.w,a,b,opt), lf=CR.lineOfFire(S.w,a,b)||{from:P(a),to:P(b)}; a.face=Math.atan2(b.x-a.x,b.z-a.z); a.aiming=true; S.camGoal={x:(a.x+b.x)/2,z:(a.z+b.z)/2}; await wait(380);
  a.ammo=Math.max(0,a.ammo-1); const res=CR.roll(o,S.rng,a.weapon); tracer(lf.from,lf.to,res.hit,S.rng); a.recoil=1; b.flinch=res.hit?1:0;
  if(a.team==='squad'){ S.stats.shots++; if(res.hit) S.stats.hits++; }
  const crossed=[]; S.w.sight(lf.from,lf.to,{shot:true,collect:crossed}); for(const x of crossed) if(x.e&&x.e.type==='window'&&x.e.win.state==='intact'){ S.w.setWindow(x.e.key,'broken'); dirtyBuild=true; }
  pop(b,res.hit?(res.crit?`CRIT −${res.dmg}`:`−${res.dmg}`):'Miss',res.hit?(res.crit?'crit':''):'miss');
  log(`${a.name} → ${b.name}: ${o.aim}%${opt.reaction?(opt.doorway?' (doorway watched)':' (overwatch)'):''}${opt.free?' (free)':''}${opt.steady?' (steady)':''} · ${res.hit?(res.crit?'crit ':'hit ')+res.dmg:'miss'}`);
  if(res.hit) harm(b,res.dmg);
  if(!opt.free) b.unaware=false; ink(b); if(dirtyBuild) rebuild(); await wait(420); a.aiming=false; drawBar(); drawHud(); return res.hit; }
function harm(b,dmg){ const r=CR.hurt(b,dmg); if(r==='down'){ log(`${b.name} is down and bleeding: ${CR.V.bleed} turns to reach them.`); pop(b,'DOWN','crit'); } else if(r==='dead') log(`${b.name} is down.`); ink(b); }
async function overwatchCheck(m){ for(const w of S.units){ if(!w.alive||!w.ow||w.team===m.team||!m.alive||w.ammo<=0) continue; if(CR.dist(w,m)>CR.V.overwatch||!CR.lineOfFire(S.w,w,m)) continue;
    const doorway=CR.atDoorway(S.w,P(m)); w.ow=false; ink(w); log(`${w.name} takes an overwatch shot${doorway?' at the doorway':''}.`); m.paused=true; await shoot(w,m,{reaction:true,doorway}); m.paused=false; } }
// a pipe bomb: an arc, then everything the blast reaches within 3 m. Cover is ignored, furniture is blown apart,
// doors are blown in and glass breaks. Walls and closed doors shelter.
async function throwBomb(u,p){ S.busy=true; S.mode='move'; clearReach(); hideHover(); u.kit.pipe--; S.stats.bombs++; const free=u.free;
  u.face=Math.atan2(p[0]-u.x,p[1]-u.z); u.aiming=true; arc.geometry.dispose(); arc.geometry=new THREE.BufferGeometry().setFromPoints(arcPoints(P(u),p,24)); arc.computeLineDistances(); arc.visible=true; await wait(500); arc.visible=false; u.aiming=false;
  const fx=new THREE.Mesh(new THREE.SphereGeometry(1,20,14),new THREE.MeshBasicMaterial({color:0xffa040,transparent:true,opacity:.85,depthWrite:false})); fx.position.set(p[0],yOf(...p)+.4,p[1]); scene.add(fx); blastFx.push({m:fx,t:0}); shake=.45;
  pop(p,'BOOM','crit'); log(`${u.name} throws a pipe bomb.`); noise(p,60,'blast');
  const reach=S.w.blastReach(p,CR.V.blastRadius);
  for(const o of reach.items){ S.w.destroyItem(o); S.destroyed.add(o.it.id); }
  for(const o of reach.openings){ if(o.e.type==='window'&&o.e.win.state!=='broken') S.w.setWindow(o.e.key,'broken'); else if(/door/.test(o.e.type)&&S.w.doorState(o.e)!=='broken') S.w.setDoor(o.e.key,'broken'); }
  if(reach.items.length) log(`The blast tears apart ${reach.items.length} piece${reach.items.length>1?'s':''} of cover.`);
  for(const {u:v,dmg} of CR.blastHits(S.w,p,S.units)){ if(v.dead) continue; v.flinch=1; if(v.down){ v.dead=true; log(`${v.name} is caught in the blast.`); ink(v); continue; } pop(v,`−${dmg}`,''); log(`${v.name} takes ${dmg} from the blast.`); harm(v,dmg); v.unaware=false; }
  rebuild(); await wait(600);
  if(free) u.free=false; else u.ap=0;
  S.busy=false; drawBar(); drawHud(); if(!checkEnd()) afterAction(u); }

// ---------- concealment ----------
function spottedCheck(){ for(const r of S.units) if(r.team==='raider'&&r.alive&&r.unaware) for(const u of squad()) if(u.alive&&CR.sees(S.w,r,P(u))){ startFight('raider',`${r.name} saw ${u.name}.`); return true; } return false; }
function raidersLook(k){ for(const r of S.units) if(r.team==='raider'&&r.alive&&r.unaware&&r.post!=='sentry'){ if(r.lookT>0){ r.lookT-=k; continue; } r.look=r.face+(S.rng()-.5)*Math.PI*1.4*k; } }

// ---------- breaching ----------
async function breach(){ const st=squad().filter(u=>u.alive&&u.stack); if(!st.length) return; S.busy=true; S.phase='breach'; clearReach(); hideHover(); drawSight(); drawEntries(); drawBar(); drawHud();
  flash('Breach',st.map(u=>`${u.name}: ${!S.w.props(u.stack.o).cross?'blows the '+(u.stack.kind==='window'?'boards':'barricade'):u.stack.kind==='window'?'through the window':'kicks the '+(u.stack.role||'side')+' door'}`).join(' · '),true);
  for(const u of st){ const e=u.stack.e, charge=!S.w.props(u.stack.o).cross;
    if(charge){ u.kit.charge--; shake=.35; pop(u.stack.out,'BLAM','crit'); }
    if(/door/.test(e.type)){ if(S.w.doorState(e)!=='broken') S.w.setDoor(e.key,'broken'); } else if(e.type==='window'&&e.win.state!=='broken') S.w.setWindow(e.key,'broken');
    u.entryMod=e.type==='window'?-10:0; }
  rebuild(); await wait(250);
  // in through the gap if the far side is clear; otherwise fire from the threshold
  await Promise.all(st.map(u=>{ const e=u.stack, t=e.in; if(!S.w.clearAt(t[0],t[1])||S.units.some(v=>v!==u&&(v.alive||v.down)&&Math.hypot(v.x-t[0],v.z-t[1])<.7)) return Promise.resolve();
    const mid=[(e.o.seg[0]+e.o.seg[2])/2,(e.o.seg[1]+e.o.seg[3])/2]; return walk(u,[{x:u.x,z:u.z},{x:mid[0],z:mid[1]},{x:t[0],z:t[1]}]); }));
  st.forEach(u=>u.stack=null);
  S.busy=false; startFight('squad','Breach!',st); }

// ---------- the fight ----------
function startFight(first,why,breachers){ S.phase='combat'; S.round=1; bannerEl.hidden=true; hideHover(); drawEntries();
  for(const u of S.units) if(u.team==='squad'&&u.alive){ u.ap=2; u.free=false; u.stack=null; u.moved=false; }
  log(why);
  if(first==='squad'){ const who=breachers||squad().filter(u=>u.alive); for(const u of who) if(u.alive) u.free=true; S.free=true; S.turn='squad';
    flash(breachers?'Breach':'First strike',`${breachers?'Breachers':'Every soldier'} get one free shot (+10 aim${breachers&&breachers.some(u=>u.entryMod)?', −10 through a window':''}; anyone unaware has no cover) before they react.`,true);
    inkAll(); select(squad().find(u=>u.alive&&u.free)||squad().find(u=>u.alive)); drawHud(); }
  else { flash('Spotted','They saw you first and scramble for cover.',false); for(const r of S.units) if(r.team==='raider') r.unaware=false; inkAll(); drawSight(); raiderPhase(true); } }
function endFree(){ S.free=false; for(const u of S.units){ u.free=false; u.entryMod=0; if(u.team==='raider') u.unaware=false; } inkAll(); flash(`Round ${S.round}`,'Your squad',true); }
function afterAction(u){ if(S.free&&!S.units.some(v=>v.free&&v.alive)) endFree();
  if((u.ap>0||u.free)&&u.alive){ select(u); return; } const next=squad().find(v=>v.alive&&(v.ap>0||v.free)); if(next) select(next); else raiderPhase(false); }
async function raiderPhase(scramble){ if(!scramble) S.minutes+=CR.V.minutesPerTurn*squad().filter(u=>u.alive||u.down&&!u.dead).length;
  S.turn='raider'; S.busy=true; S.mode='move'; clearReach(); hideHover(); drawSight(); drawBar(); drawHud(); if(!scramble) flash(`Round ${S.round}`,'Raiders',false); await wait(600);
  for(const b of CR.morale(S.units,S.rng)){ log(`${b.name} breaks and runs.`); pop(b,'RUNS','info'); ink(b); }
  for(const r of S.units.filter(u=>u.team==='raider'&&u.alive)){ r.ap=scramble?1:2; r.hunker=false; r.ow=false; S.camGoal={x:r.x,z:r.z};
    while(r.ap>0&&r.alive&&squad().some(u=>u.alive)){ const a=CR.decide(S.w,r,S.units,S.rng,{scramble});
      if(a.type==='shoot'){ await shoot(r,a.target); r.ap=0; }
      else if(a.type==='reload'){ r.ammo=r.weapon.ammo; r.ap--; log(`${r.name} reloads.`); await wait(300); }
      else if(a.type==='escape'){ r.alive=false; r.fled=true; r.fig.root.visible=false; log(`${r.name} gets away.`); break; }
      else if(a.type==='move'&&a.path){ r.ap--; await walk(r,a.path.points); if(dirtyBuild) rebuild(); if(scramble) break; }
      else { r.ow=true; r.ap=0; ink(r); log(`${r.name} watches the doorways.`); } }
    if(scramble&&r.alive&&r.ap>0){ r.ow=true; r.ap=0; ink(r); }
    S.minutes+=CR.V.minutesPerTurn; drawHud(); if(checkEnd()){ S.busy=false; return; } }
  if(!scramble) S.round++; S.busy=false; S.turn='squad';
  // the squad's turn begins: the bleeding lose a turn, Run and gun cools down
  for(const u of squad()){ if(u.down&&!u.stable&&!u.dead){ u.bleed--; if(u.bleed<=0){ u.dead=true; log(`${u.name} bled out.`); } else log(`${u.name} is bleeding out: ${u.bleed} turn${u.bleed>1?'s':''} left.`); ink(u); }
    if(u.alive){ u.ap=2; u.hunker=false; u.moved=false; if(u.cooldown) u.cooldown--; } }
  if(checkEnd()) return;
  flash(`Round ${S.round}`,'Your squad',true); select(squad().find(u=>u.alive)); drawHud(); }
function endSquadTurn(){ if(S.free){ endFree(); select(squad().find(u=>u.alive&&u.ap>0)); return; } for(const u of squad()){ u.ap=0; u.free=false; } raiderPhase(false); }
function checkEnd(){ const s=squad().some(u=>u.alive), r=S.units.some(u=>u.team==='raider'&&u.alive); if(r&&s) return false;
  S.phase='over'; S.busy=false; S.mode='move'; clearReach(); hideHover(); drawSight();
  const mins=S.minutes-14*60, rs=S.units.filter(u=>u.team==='raider'), sq=squad();
  const line=`${rs.filter(u=>u.dead).length} killed, ${rs.filter(u=>u.fled).length} fled · squad: ${sq.filter(u=>u.alive).length} standing, ${sq.filter(u=>u.down&&!u.dead).length} down, ${sq.filter(u=>u.dead).length} dead · ${S.stats.hits}/${S.stats.shots} shots hit${S.stats.bombs?`, ${S.stats.bombs} pipe bomb${S.stats.bombs>1?'s':''}`:''} · ${Math.floor(mins/60)} h ${mins%60} min of daylight`;
  if(!r) flash('Building clear',line,true,true); else flash('Squad lost','Nobody is left standing. '+line,false,true);
  log(line); inkAll(); drawBar(); drawHud(); return true; }

// ---------- input ----------
$('bar').addEventListener('click',async e=>{ const b=e.target.closest('button'); if(!b||b.disabled) return;
  if(b.dataset.i!==undefined){ const u=S.units[+b.dataset.i]; if(u.alive&&S.turn==='squad'&&!S.busy) select(u); return; }
  if(b.dataset.t!==undefined){ const u=S.sel, t=S.units[+b.dataset.t]; showAim(null); S.busy=true; clearReach(); const free=u.free, o=shotOdds(u,t); await shoot(u,t,{free,steady:u.role==='sharpshooter'&&u.ap>=2&&!free,odds:o}); if(free) u.free=false; else u.ap=0; S.busy=false; S.mode='move'; if(!checkEnd()) afterAction(u); return; }
  if(b.dataset.aid!==undefined){ aid(S.sel,S.units[+b.dataset.aid]); return; }
  act(b.dataset.a); });
$('bar').addEventListener('pointerover',e=>{ const b=e.target.closest('button[data-t]'); showAim(b?S.sel:null,b?S.units[+b.dataset.t]:null); if(b){ hoverEl.innerHTML=whyHtml(shotOdds(S.sel,S.units[+b.dataset.t])); } });
$('bar').addEventListener('pointerout',e=>{ if(e.target.closest('button[data-t]')){ showAim(null); hoverEl.textContent=''; } });
function aid(u,v){ if(!u||u.kit.aid<=0) return; u.kit.aid--; u.ap--;
  if(v.down&&!v.stable){ v.stable=true; log(`${u.name} stops ${v.name}'s bleeding.`); pop(v,'stable','info'); }
  else if(v.down&&v.stable){ v.down=false; v.alive=true; v.hp=2; v.ap=0; log(`${u.name} gets ${v.name} back on their feet.`); pop(v,'+2','info'); }
  else { v.hp=Math.min(v.max,v.hp+CR.V.aidHeal); log(`${u.name} patches up ${v===u?'themself':v.name}: +${CR.V.aidHeal}.`); pop(v,'+'+CR.V.aidHeal,'info'); }
  ink(v); S.mode='move'; afterAction(u); }
async function act(a){ const u=S.sel;
  if(a==='restart'){ setup(); return; } if(a==='reroll'){ S.seed++; setup(); return; }
  if(!u||S.busy) return;
  if(a==='stack'){ if(u.stack){ u.stack=null; drawBar(); return; } const e=entryAt(u); if(!e) return; S.busy=true; clearReach(); await walk(u,[{x:u.x,z:u.z},{x:e.out[0],z:e.out[1]}]); S.busy=false; u.stack=e;
    u.face=Math.atan2(e.in[0]-e.out[0],e.in[1]-e.out[1]); if(!spottedCheck()){ drawReach(); drawBar(); } return; }
  if(a==='breach'){ breach(); return; }
  if(a==='fire'){ startFight('squad','The squad opens fire.'); return; }
  if(a==='wait'){ if(S.phase==='explore'){ S.minutes+=1; raidersLook(1); if(!spottedCheck()) drawSight(); drawHud(); } else endSquadTurn(); return; }
  if(a==='shoot'){ if(u.ammo<=0) return; S.mode='shoot'; clearReach(); drawBar(); return; }
  if(a==='back'){ S.mode='move'; showAim(null); arc.visible=false; hideHover(); drawReach(); drawBar(); return; }
  if(a==='ow'){ u.ow=true; u.ap=0; ink(u); log(`${u.name} is on overwatch.`); afterAction(u); return; }
  if(a==='hunker'){ u.hunker=true; u.ap=0; log(`${u.name} hunkers down: cover counts for more.`); afterAction(u); return; }
  if(a==='reload'){ u.ammo=u.weapon.ammo; u.ap--; log(`${u.name} reloads the ${u.weapon.name.toLowerCase()}.`); afterAction(u); return; }
  if(a==='throw'){ if(u.kit.pipe>0){ S.mode='throw'; clearReach(); drawBar(); } return; }
  if(a==='aid'){ S.mode='aid'; drawBar(); return; }
  if(a==='rungun'){ if(u.cooldown) return; u.ap+=1; u.cooldown=CR.V.runGunCooldown; log(`${u.name} runs and guns: one more action.`); pop(u,'+1 action','info'); select(u); return; }
  if(a==='close'){ const o=openDoorBeside(u); if(o){ S.w.setDoor(o.e.key,'closed'); rebuild(); u.ap--; log(`${u.name} closes the door.`); afterAction(u); } return; }
  if(a==='end') endSquadTurn(); }
addEventListener('keydown',e=>{ if(e.target.tagName==='SELECT') return; const k=e.key;
  if(k==='q'||k==='Q') view.az-=Math.PI/2; else if(k==='e'||k==='E') view.az+=Math.PI/2;
  if(S.turn!=='squad'||S.busy) return; const u=S.sel;
  if(k==='1') act(S.phase==='explore'?'fire':'shoot'); else if(k==='2') act('ow'); else if(k==='3') act('hunker'); else if(k==='4') act('reload'); else if(k==='b'||k==='B') act('breach');
  else if(k==='5'&&u) act(u.role==='breacher'?'throw':u.role==='medic'?'aid':u.role==='ranger'?'rungun':'');
  else if(k==='Backspace'){ e.preventDefault(); act(S.phase==='explore'?'wait':'end'); } else if(k==='Escape') act('back');
  else if(k==='Tab'){ e.preventDefault(); const sq=squad().filter(u=>u.alive); select(sq[(sq.indexOf(S.sel)+1)%sq.length]); } });
const canvas3=renderer.domElement, ray=new THREE.Raycaster(), ndc=new THREE.Vector2(), plane=new THREE.Plane(new THREE.Vector3(0,1,0),-.08), hitP=new THREE.Vector3();
function pointUnder(ev){ const r=canvas3.getBoundingClientRect(); ndc.set((ev.clientX-r.left)/r.width*2-1,-(ev.clientY-r.top)/r.height*2+1); ray.setFromCamera(ndc,camera); return ray.ray.intersectPlane(plane,hitP)?[hitP.x,hitP.z]:null; }
// where a click at p would send the selected unit: snapped into nearby cover, if that spot is in reach
function target(p){ if(!p||!S.F) return null; const q=S.w.snap(p), ct=S.w.costTo(S.F,q); if(ct&&!ct.over) return {p:q,cost:ct.cost,snapped:q!==p};
  const c2=S.w.costTo(S.F,p); return c2&&!c2.over?{p,cost:c2.cost,snapped:false}:null; }
// where a pipe bomb thrown toward p would land: within range and in sight of the thrower
function landing(u,p){ if(!p) return null; const d=Math.hypot(p[0]-u.x,p[1]-u.z); let q=p; if(d>CR.V.throwRange){ q=[u.x+(p[0]-u.x)/d*CR.V.throwRange,u.z+(p[1]-u.z)/d*CR.V.throwRange]; }
  const from=[P(u),...S.w.leans(P(u),q)]; return from.some(f=>S.w.sight(f,q,{shot:true}))?q:null; }
let drag=null;
canvas3.addEventListener('pointerdown',e=>{ drag={x:e.clientX,y:e.clientY,pan:e.button===2||e.shiftKey,moved:0}; canvas3.setPointerCapture(e.pointerId); });
canvas3.addEventListener('pointermove',e=>{ if(!drag){ hover(pointUnder(e)); return; } const dx=e.clientX-drag.x, dy=e.clientY-drag.y; drag.x=e.clientX; drag.y=e.clientY; drag.moved+=Math.abs(dx)+Math.abs(dy);
  if(drag.moved<6) return; S.camGoal=null;
  if(drag.pan){ const s=view.dist*.0016, ca=Math.cos(view.az), sa=Math.sin(view.az); view.target.x-=(dx*ca-dy*sa)*s; view.target.z-=(-dx*sa-dy*ca)*s; }
  else { view.az-=dx*.008; view.el=clamp(view.el+dy*.006,.3,1.45); } });
canvas3.addEventListener('pointerup',e=>{ const click=drag&&drag.moved<6; drag=null; if(!click) return; const p=pointUnder(e); if(!p) return;
  if(S.mode==='throw'&&S.sel&&!S.busy){ const q=landing(S.sel,p); if(q) throwBomb(S.sel,q); else log('No clear throw there.'); return; }
  const u=S.units.find(v=>v.alive&&v.team==='squad'&&Math.hypot(v.x-p[0],v.z-p[1])<.55); if(u&&S.turn==='squad'&&!S.busy){ select(u); return; }
  if(S.mode!=='move'||S.turn!=='squad'||S.busy||!S.sel) return; const t=target(p); if(t) moveTo(S.sel,t.p); else log('Out of reach this turn.'); });
canvas3.addEventListener('contextmenu',e=>e.preventDefault());
canvas3.addEventListener('wheel',e=>{ e.preventDefault(); view.dist=clamp(view.dist*Math.exp(e.deltaY*.0012),6,90); },{passive:false});
function hideHover(){ ghost.visible=false; route.visible=false; while(glyphs.children.length) glyphs.children.pop(); hoverEl.textContent=''; if(S.mode!=='throw') for(const m of ribbons.children.filter(m=>m.userData.blast)){ ribbons.remove(m); m.geometry.dispose(); } }
function hover(p){ if(S.mode==='throw'){ hoverThrow(p); return; } hideHover(); if(!p||!S.w||S.phase==='over'||S.busy||S.turn!=='squad'||S.mode!=='move') return; const w=S.w, t=target(p);
  const parts=[];
  if(!t){ const it=w.obs.find(o=>o.kind==='item'&&!o.destroyed&&p[0]>=o.box.x0&&p[0]<=o.box.x1&&p[1]>=o.box.z0&&p[1]<=o.box.z1); if(it) parts.push(`${it.it.key}: ${it.it.spec.cover} cover${it.it.spec.cover==='full'&&it.h>=w.EYE?', blocks sight':''}`); else if(S.F) parts.push('Out of reach'); hoverEl.textContent=parts.join('\n'); return; }
  ghost.position.set(t.p[0],yOf(...t.p)+.05,t.p[1]); ghost.visible=true;
  const path=w.pathTo(S.F,t.p); if(path){ route.geometry.dispose(); route.geometry=new THREE.BufferGeometry().setFromPoints(path.points.map(q=>new THREE.Vector3(q.x,yOf(q.x,q.z)+.1,q.z))); route.computeLineDistances(); route.visible=true; }
  // a marker toward each foe: tall gold full cover, short gold half, flat red flanked
  const fs=S.units.filter(r=>r.team==='raider'&&r.alive), cv=fs.map(r=>w.coverFrom(t.p,P(r)));
  fs.forEach((r,i)=>{ const a=Math.atan2(r.x-t.p[0],r.z-t.p[1]), h=cv[i]===2?1:cv[i]===1?.5:.06, m=new THREE.Mesh(glyphG,glyphM[cv[i]]); m.scale.set(.32,h,.05); m.rotation.y=a; m.position.set(t.p[0]+Math.sin(a)*.62,yOf(...t.p)+h/2,t.p[1]+Math.cos(a)*.62); m.renderOrder=7; glyphs.add(m); });
  parts.push(`Cover vs ${fs.length}: ${cv.filter(v=>v===2).length} full · ${cv.filter(v=>v===1).length} half · flanked by ${cv.filter(v=>v===0).length}`);
  parts.push(`${t.cost.toFixed(1)} effective m · ${S.phase==='explore'?'move':t.cost<=CR.V.move?'1 action':'dash, 2 actions'}${t.snapped?' · into cover':''}`);
  if(S.phase==='explore'){ const e=w.entries().find(x=>Math.hypot(x.out[0]-t.p[0],x.out[1]-t.p[1])<1.1); if(e) parts.push(`${e.kind==='window'?'Window ('+e.e.win.state+')':(e.role||'side')+' door ('+w.doorState(e.e)+')'}: ${usable(e,S.sel)?'stand here to stack':'only a Breacher\'s charge gets through'}`); }
  hoverEl.textContent=parts.join('\n'); hoverEl.style.whiteSpace='pre-line'; }
function hoverThrow(p){ ghost.visible=false; route.visible=false; while(glyphs.children.length) glyphs.children.pop(); for(const m of ribbons.children.filter(m=>m.userData.blast)){ ribbons.remove(m); m.geometry.dispose(); } arc.visible=false;
  const u=S.sel; if(!u||!p){ hoverEl.textContent=''; return; } const q=landing(u,p); if(!q){ hoverEl.textContent='No clear throw there'; return; }
  const m=ribbonMesh(ring(q,CR.V.blastRadius),ribbonM.blast,.18); m.userData.blast=true; ribbons.add(m);
  arc.geometry.dispose(); arc.geometry=new THREE.BufferGeometry().setFromPoints(arcPoints(P(u),q,24)); arc.computeLineDistances(); arc.visible=true;
  const hits=CR.blastHits(S.w,q,S.units).filter(h=>!h.u.dead), reach=S.w.blastReach(q,CR.V.blastRadius);
  for(const h of hits){ const g=new THREE.Mesh(glyphG,glyphM[0]); g.scale.set(.5,.08,.5); g.position.set(h.u.x,yOf(h.u.x,h.u.z)+2.1,h.u.z); glyphs.add(g); }
  hoverEl.textContent=`Pipe bomb: ${hits.filter(h=>h.u.team==='raider').map(h=>h.u.name+' −'+h.dmg).join(', ')||'no raiders'}${hits.some(h=>h.u.team==='squad')?' · hits your own: '+hits.filter(h=>h.u.team==='squad').map(h=>h.u.name).join(', '):''}\nDestroys ${reach.items.length} piece${reach.items.length===1?'':'s'} of cover · ignores cover`; hoverEl.style.whiteSpace='pre-line'; }

// ---------- per frame ----------
let last=performance.now();
function resize(){ const st=$('stage'), w=st.clientWidth, h=st.clientHeight; renderer.setSize(w,h,false); camera.aspect=w/Math.max(1,h); camera.updateProjectionMatrix(); }
new ResizeObserver(resize).observe($('stage'));
const tmpV=new THREE.Vector3();
function frame(now){ requestAnimationFrame(frame); const dt=Math.min(.05,(now-last)/1000)*S.timeScale; last=now; if(!S.w) return;   // timeScale: tests on slow software rendering speed it up
  for(const m of glowMats) m.uniforms.t.value=now/1000;
  for(let i=waits.length-1;i>=0;i--){ waits[i].t-=dt*1000; if(waits[i].t<=0){ waits[i].r(); waits.splice(i,1); } }
  const st=$('stage'), W=st.clientWidth, H=st.clientHeight;
  for(const p of pops){ p.t+=dt; tmpV.set(p.x,p.y+p.t*1.1,p.z).project(camera); p.el.style.left=((tmpV.x+1)/2*W)+'px'; p.el.style.top=((1-tmpV.y)/2*H)+'px'; p.el.style.opacity=String(Math.max(0,1-p.t/1.6)); }
  for(let i=pops.length-1;i>=0;i--) if(pops[i].t>1.6){ pops[i].el.remove(); pops.splice(i,1); }
  for(const t of tracers) t.t+=dt; for(let i=tracers.length-1;i>=0;i--){ const t=tracers[i]; t.l.material.opacity=Math.max(0,1-t.t/.35); if(t.t>.35){ scene.remove(t.l); t.l.geometry.dispose(); tracers.splice(i,1); } }
  for(const b of blastFx){ b.t+=dt; b.m.scale.setScalar(.5+b.t*9); b.m.material.opacity=Math.max(0,.85-b.t*2.4); } for(let i=blastFx.length-1;i>=0;i--) if(blastFx[i].t>.4){ scene.remove(blastFx[i].m); blastFx[i].m.geometry.dispose(); blastFx.splice(i,1); }
  for(const u of S.units){ const f=u.fig; let walking=false; if(!f.root.visible) continue;
    if(u.route&&!u.paused){ if(!u.route.length||!u.alive){ u.route=null; const r=u.done; u.done=null; r&&r(); }
      else { const q=u.route[0], dx=q.x-u.x, dz=q.z-u.z, d=Math.hypot(dx,dz), sp=3.2*dt;
        if(q.through&&!q.opened&&d<.75){ q.opened=true; opening(u,q.through); if(dirtyBuild) rebuild(); }
        const step=Math.min(d,sp); if(d>1e-6){ u.x+=dx/d*step; u.z+=dz/d*step; u.face=Math.atan2(dx,dz); } u.trav+=step; if(d<=sp) u.route.shift();
        walking=true;
        if(u.trav>=.3){ u.trav=0;
          if(S.phase==='explore'&&u.team==='squad'&&spottedCheck()) u.route=[];
          else if(S.phase==='combat') overwatchCheck(u); } } }
    if(u.team==='raider'&&u.unaware&&u.alive&&S.phase==='explore'){ let a=u.look-u.face; a=Math.atan2(Math.sin(a),Math.cos(a)); const was=u.face; u.face+=a*Math.min(1,dt*1.5); if(Math.abs(u.face-was)>.002) u.turned=true; }
    let a=u.face-f.root.rotation.y; a=Math.atan2(Math.sin(a),Math.cos(a)); f.root.rotation.y+=a*Math.min(1,dt*9);
    const y=yOf(u.x,u.z); f.y=f.y===undefined?y:f.y+(y-f.y)*Math.min(1,dt*12); f.root.position.set(u.x,f.y,u.z);
    if(!u.alive){ f.root.rotation.x+=((-Math.PI/2+.08)-f.root.rotation.x)*Math.min(1,dt*5); f.root.position.y=f.y+.25; continue; }
    if(f.root.rotation.x) f.root.rotation.x+=(0-f.root.rotation.x)*Math.min(1,dt*5);   // getting back up after first aid
    const J=Object.assign({},S.phase!=='explore'||u.team==='squad'?FigureKit.POSES.ready:FigureKit.POSES.stand), ph=now/1000*(u.fleeing?13:9)+u.x;
    if(walking) Object.assign(J,{lgR:Math.sin(ph)*.5,lgL:-Math.sin(ph)*.5,knR:Math.max(0,-Math.sin(ph))*.9+.06,knL:Math.max(0,Math.sin(ph))*.9+.06,torsoX:.12,shRx:-.9,shLx:-.7,elR:-.5,elL:-1});
    else if(u.aiming||u.ow) Object.assign(J,{shRx:-1.45,shRz:-.1,elR:-.12,shLx:-1.25,shLz:.4,elL:-.55,torsoY:.15,headX:0});
    else if(u.hunker||(S.phase==='explore'&&u.team==='squad'&&u.stack)) Object.assign(J,{bodyY:-.38,lgR:-1.2,knR:1.7,lgL:-.5,knL:1.9,torsoX:.55,headX:.2});
    if(u.flinch){ J.torsoX-=.4*u.flinch; u.flinch=Math.max(0,u.flinch-dt*3); } if(u.recoil){ J.shRx+=.25*u.recoil; u.recoil=Math.max(0,u.recoil-dt*5); }
    const k=1-Math.exp(-dt*12); f.j=f.j||Object.assign({},J); for(const key in J) f.j[key]+=(J[key]-f.j[key])*k; FigureKit.applyPose(f,f.j); }
  // the raiders' fans follow their heads while you are concealed (redrawn a few times a second, not every frame)
  if(S.phase==='explore'&&S.sight&&(frame.t=(frame.t||0)+dt)>.25){ frame.t=0; if(S.units.some(u=>u.turned)){ S.units.forEach(u=>u.turned=false); drawSight(); } }
  if(S.camGoal){ view.target.x+=(S.camGoal.x-view.target.x)*Math.min(1,dt*2.5); view.target.z+=(S.camGoal.z-view.target.z)*Math.min(1,dt*2.5); if(S.sel&&!S.busy&&S.turn==='squad'&&S.sel.alive) S.camGoal={x:S.sel.x,z:S.sel.z}; }
  placeCamera(); if(shake>0){ shake=Math.max(0,shake-dt); const k=shake*.35; camera.position.x+=(Math.random()-.5)*k; camera.position.y+=(Math.random()-.5)*k; } applyView(); renderer.render(scene,camera); }

// ---------- header ----------
$('bSel').onchange=()=>{ S.seed=0; setup(); }; $('hSel').onchange=()=>setup();
$('rerollBtn').onclick=()=>{ S.seed++; setup(); }; $('restartBtn').onclick=()=>setup();
$('sightBtn').onclick=()=>{ S.sight=!S.sight; $('sightBtn').setAttribute('aria-pressed',S.sight); drawSight(); };
const MODES=['cutaway','low','shell'], ML={cutaway:'Walls: cutaway',low:'Walls: low',shell:'Walls: full + roof'};
$('wallsBtn').onclick=()=>{ view.mode=MODES[(MODES.indexOf(view.mode)+1)%MODES.length]; $('wallsBtn').textContent=ML[view.mode]; };
resize(); setup(); requestAnimationFrame(frame);
// for tests and the console
window.__combat={S,CR,select,moveTo,act,breach,startFight,setup,entryAt,target,usable,landing,throwBomb,aid,shotOdds};
})();
