// ---------- interior combat demonstration: plan, then everyone moves at once ----------
// The building is generated by the interiors generator (tools/interiors, its own topic) and drawn by its renderer;
// props scatter and tip over, and walls crack, hole and breach by their build-up, all with the interiors code.
// Figures move with the shared motion module (tools/motion).
//
// Pacing. Exploring runs in real time. In a fight each round has two halves:
//   plan: give each soldier a move (left click) and an action (right click a raider or a thing for its options);
//   go:   the whole squad carries out its orders at the same moment. Shots fire as each soldier arrives, so two
//         soldiers ordered onto the same raider may find the second shot has nothing left to hit.
// Then the raiders all act at once in the same way.
// What you see is what the squad sees: raiders out of everyone's sight are hidden (with a mark where they were last seen).
// Rules: tools/combat/rules.js. Space: tools/combat/space.js.
(()=>{
const CR=CombatRules, SP=InteriorSpace, $=id=>document.getElementById(id);
const hudEl=$('hud'), hoverEl=$('hover'), logEl=$('log'), bannerEl=$('banner'), unitsEl=$('units'), actsEl=$('acts'), badgesEl=$('badges'), ctxEl=$('ctx');
const INKS={selected:0xe0a526,calm:0x1d1814,overwatch:0x2f9fc4,concealed:0x5b6fa8,wounded:0xc23b2e,panicked:0x9b4fc4,raider:0x6e1a10,dead:0x77726a};
const ROLES_ORDER=['ranger','sharpshooter','breacher','medic'], FIRST=['Rosa','Dev','Malik','June','Tomas','Ana','Kofi','Lena','Rafael','Sana','Ivo','Nadia','Oskar','Yuki','Dario','Amara','Felix','Ines','Hugo','Leila'];
const NICK={ranger:['Blade','Havoc','Viper'],sharpshooter:['Hawk','Needle','Owl'],breacher:['Boomer','Anvil','Crater'],medic:['Patch','Doc','Stitch']};
const SQUAD_COL=[0xf3d38a,0x9fd3e6,0xffa07a,0xa8e6a1];
// a low camera with a long lens: you read the room from the squad's level, not from above the roofs
const FOV=26; view.marks=false; view.mode='cutaway'; view.el=.58; view.dist=30; camera.fov=FOV; camera.updateProjectionMatrix();
renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));
scene.add(new THREE.AmbientLight(0xffffff,.18));

// ---------- state ----------
const S={labels:true,timeScale:1,slow:1,w:null,G:null,rec:null,units:[],sel:null,phase:'explore',busy:false,mode:'move',round:1,minutes:14*60,seed:0,F:null,camGoal:null,camHold:0,sight:true,free:false,fps:false,destroyed:new Set(),stats:null,mission:null,declined:new Set(),prompt:false};
let dirtyBuild=false, shake=0;
const order=SITES.map((s,i)=>i).sort((a,b)=>(SITES[b].id==='newriver/2_2/0')-(SITES[a].id==='newriver/2_2/0'));
{ const o=document.createElement('option'); o.value='test'; o.textContent='Test range · every combat case'; $('bSel').appendChild(o); }
for(const i of order){ const s=SITES[i]; const o=document.createElement('option'); o.value=i; o.textContent=(s.name||(s.house?'House':'Building'))+' · '+s.id; $('bSel').appendChild(o); }
const P=u=>[u.x,u.z];
const yOf=(x,z)=>S.w.floorY(x,z);
const roleOf=u=>CR.ROLES[u.role];
const physicsOn=()=>typeof CANNON!=='undefined'&&typeof grenade==='function';
const waitSim=async()=>{ for(let k=0;k<400&&typeof SIM!=='undefined'&&SIM;k++) await new Promise(r=>setTimeout(r,25)); };
const planning=()=>S.phase==='plan'&&!S.busy;

// ---------- the roster: ranks and the memorial live in this browser (per viewer, safe to lose) ----------
const STORE='nightfall-combat-roster';
function loadRoster(){ try{ const r=JSON.parse(localStorage.getItem(STORE)||'null'); if(r&&r.squad&&r.squad.length===4) return r; }catch(e){} return freshRoster(); }
function freshRoster(){ return {squad:ROLES_ORDER.map((role,i)=>({name:FIRST[i],role,xp:0,kills:0,missions:0})),memorial:[],next:4}; }
function saveRoster(){ try{ localStorage.setItem(STORE,JSON.stringify(S.roster)); }catch(e){} }
S.roster=loadRoster();
const rankName=xp=>CR.RANKS[CR.rankOf(xp)];

// ---------- overlays ----------
// reach: a faint tint over everything in range, and a glowing band along the edge of one action (blue) and a dash (gold)
const fillG=new THREE.PlaneGeometry(.52,.52); fillG.rotateX(-Math.PI/2);
const fill=new THREE.InstancedMesh(fillG,new THREE.MeshBasicMaterial({transparent:true,opacity:.07,depthWrite:false}),20000); fill.instanceColor=new THREE.InstancedBufferAttribute(new Float32Array(20000*3),3); fill.count=0; fill.frustumCulled=false; fill.renderOrder=4; scene.add(fill);
const glowMats=[];
function glowMat(color){ const m=new THREE.ShaderMaterial({uniforms:{c:{value:new THREE.Color(color)},t:{value:0}},transparent:true,depthWrite:false,side:THREE.DoubleSide,
  vertexShader:'attribute float side; varying float vS; void main(){ vS=side; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0); }',
  fragmentShader:'uniform vec3 c; uniform float t; varying float vS; void main(){ float k=1.0-abs(vS); float core=smoothstep(0.78,0.97,k); float halo=pow(k,1.7)*(0.72+0.2*sin(t*2.6)); vec3 col=mix(c,vec3(1.0),core*0.6); gl_FragColor=vec4(col,clamp(max(core,halo),0.0,1.0)); }'});
  glowMats.push(m); return m; }
const ribbonM={near:glowMat(0x4aa3ff),far:glowMat(0xffb42e),blast:glowMat(0xff5a3a),evac:glowMat(0x3fdc8f)};
const ribbons=new THREE.Group(); scene.add(ribbons);
const evacRing=new THREE.Group(); scene.add(evacRing);
const tmpM=new THREE.Matrix4(), col=new THREE.Color();
function clearReach(){ fill.count=0; while(ribbons.children.length){ ribbons.children.pop().geometry.dispose(); } }
function contour(F,T){ const w=S.w, NW=w.NW, NH=w.NH, out=[]; const v=n=>isFinite(F.cost[n])?F.cost[n]:T+3;
  const lerp=(ax,az,av,bx,bz,bv)=>{ const t=(T-av)/(bv-av); return [ax+(bx-ax)*t,az+(bz-az)*t]; };
  for(let j=0;j<NH-1;j++) for(let i=0;i<NW-1;i++){ const a=j*NW+i, b=a+1, c=a+NW+1, d=a+NW, va=v(a), vb=v(b), vc=v(c), vd=v(d);
    const k=(va<=T?1:0)|(vb<=T?2:0)|(vc<=T?4:0)|(vd<=T?8:0); if(k===0||k===15) continue;
    const ax=w.nodeX(a), az=w.nodeZ(a), bx=w.nodeX(b), bz=w.nodeZ(b), cx=w.nodeX(c), cz=w.nodeZ(c), dx=w.nodeX(d), dz=w.nodeZ(d);
    const AB=()=>lerp(ax,az,va,bx,bz,vb), BC=()=>lerp(bx,bz,vb,cx,cz,vc), CD=()=>lerp(cx,cz,vc,dx,dz,vd), DA=()=>lerp(dx,dz,vd,ax,az,va);
    const segs={1:[[DA,AB]],2:[[AB,BC]],3:[[DA,BC]],4:[[BC,CD]],5:[[DA,AB],[BC,CD]],6:[[AB,CD]],7:[[DA,CD]],8:[[CD,DA]],9:[[CD,AB]],10:[[AB,BC],[CD,DA]],11:[[CD,BC]],12:[[BC,DA]],13:[[BC,AB]],14:[[AB,DA]]}[k];
    for(const [p,q] of segs) out.push([p(),q()]); }
  return out; }
function ribbonMesh(segs,mat,W){ W=W||.3; const pos=[], side=[]; for(const [a,b] of segs){ const dx=b[0]-a[0], dz=b[1]-a[1], L=Math.hypot(dx,dz)||1, nx=-dz/L*W, nz=dx/L*W, ya=yOf(a[0],a[1])+.05, yb=yOf(b[0],b[1])+.05;
    pos.push(a[0]+nx,ya,a[1]+nz, b[0]+nx,yb,b[1]+nz, b[0]-nx,yb,b[1]-nz, a[0]+nx,ya,a[1]+nz, b[0]-nx,yb,b[1]-nz, a[0]-nx,ya,a[1]-nz); side.push(1,1,-1,1,-1,-1); }
  const g=new THREE.BufferGeometry(); g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3)); g.setAttribute('side',new THREE.Float32BufferAttribute(side,1)); const m=new THREE.Mesh(g,mat); m.renderOrder=5; m.frustumCulled=false; return m; }
function ring(c,r){ const segs=[], n=48; for(let k=0;k<n;k++){ const a=k/n*Math.PI*2, b=(k+1)/n*Math.PI*2; segs.push([[c[0]+Math.sin(a)*r,c[1]+Math.cos(a)*r],[c[0]+Math.sin(b)*r,c[1]+Math.cos(b)*r]]); } return segs; }
// the selected soldier's reach this round, given what is already ordered (an action keeps one action back)
function drawReach(){ clearReach(); const u=S.sel; S.F=null; if(!u||!u.alive||u.team!=='squad'||S.busy||S.prompt) return;
  if(S.phase==='explore'){ S.F=S.w.field(P(u),80,others(u)); return; }
  if(S.phase!=='plan') return; const mv=u.move||CR.V.move, b=moveBudget(u); S.F=S.w.field(P(u),Math.max(b,2*mv),others(u)); if(!b) return;
  for(let n=0;n<S.F.cost.length;n++){ const c=S.F.cost[n]; if(!(c<=b)||fill.count>=20000) continue; tmpM.makeTranslation(S.w.nodeX(n),yOf(S.w.nodeX(n),S.w.nodeZ(n))+.03,S.w.nodeZ(n)); fill.setMatrixAt(fill.count,tmpM); fill.setColorAt(fill.count,col.setHex(c<=mv?0x3f8fd1:0xe0a526)); fill.count++; }
  fill.instanceMatrix.needsUpdate=true; fill.instanceColor.needsUpdate=true;
  if(b>mv) ribbons.add(ribbonMesh(contour(S.F,b),ribbonM.far)); ribbons.add(ribbonMesh(contour(S.F,Math.min(b,mv)),ribbonM.near)); }
function drawEvac(){ while(evacRing.children.length) evacRing.children.pop().geometry.dispose(); const M=S.mission; if(!M||!M.stashTaken||S.phase==='over') return; evacRing.add(ribbonMesh(ring(M.evac,M.evacR),ribbonM.evac,.22)); }
// sight: fans cut where walls and tall things stop the eye (only for raiders the squad can see)
const fans=new THREE.Group(); scene.add(fans);
const fanM={raider:new THREE.MeshBasicMaterial({color:0xc23b2e,transparent:true,opacity:.2,depthWrite:false,side:THREE.DoubleSide}),own:new THREE.MeshBasicMaterial({color:0x3fae7f,transparent:true,opacity:.12,depthWrite:false,side:THREE.DoubleSide})};
function fan(x,z,a0,a1,maxD,mat){ const pos=[], n=Math.max(8,Math.ceil((a1-a0)/(Math.PI/120))), y=yOf(x,z)+.06; let prev=null;
  for(let k=0;k<=n;k++){ const a=a0+(a1-a0)*k/n, d=S.w.castRay([x,z],a,maxD), p=[x+Math.sin(a)*d,z+Math.cos(a)*d]; if(prev) pos.push(x,y,z, prev[0],y,prev[1], p[0],y,p[1]); prev=p; }
  const g=new THREE.BufferGeometry(); g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3)); const m=new THREE.Mesh(g,mat); m.renderOrder=3; return m; }
function drawSight(){ while(fans.children.length){ fans.children.pop().geometry.dispose(); } if(!S.sight||!S.w) return;
  if(S.phase==='explore'){ for(const r of S.units) if(r.team==='raider'&&r.alive&&r.unaware&&r.vis){ fans.add(fan(r.x,r.z,r.face-CR.V.cone,r.face+CR.V.cone,CR.V.sight,fanM.raider)); fans.add(fan(r.x,r.z,0,Math.PI*2,CR.V.around,fanM.raider)); } }
  else if(S.phase==='plan'&&S.sel&&S.sel.alive&&S.sel.team==='squad'){ const p=planned(S.sel); fans.add(fan(p[0],p[1],0,Math.PI*2,CR.V.spot,fanM.own)); } }
// hover and planning marks: a ring where the soldier would stand, the route there, a marker toward each known foe
const ringG=new THREE.RingGeometry(.3,.4,28); ringG.rotateX(-Math.PI/2);
const ghost=new THREE.Mesh(ringG,new THREE.MeshBasicMaterial({color:0xf3d38a,transparent:true,opacity:.9,depthWrite:false})); ghost.renderOrder=6; ghost.visible=false; scene.add(ghost);
const route=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:0xf3d38a,dashSize:.25,gapSize:.15})); route.visible=false; scene.add(route);
const glyphs=new THREE.Group(); scene.add(glyphs);
const glyphG=new THREE.BoxGeometry(1,1,1), glyphM={2:new THREE.MeshBasicMaterial({color:0xe0a526}),1:new THREE.MeshBasicMaterial({color:0xe0a526,transparent:true,opacity:.6}),0:new THREE.MeshBasicMaterial({color:0xc23b2e})};
const orderViz=new THREE.Group(); scene.add(orderViz);
const entryMarks=new THREE.Group(); scene.add(entryMarks);
function drawEntries(){ while(entryMarks.children.length) entryMarks.children.pop(); if(S.phase!=='explore') return;
  for(const e of S.w.entries()){ const ok=usable(e,S.sel), blocked=!S.w.props(e.o).cross; if(!ok&&!blocked) continue;
    const m=new THREE.Mesh(ringG,new THREE.MeshBasicMaterial({color:blocked?(ok?0xff7a4a:0x6c6a66):e.kind==='window'?0x9fd3e6:0xe0a526,transparent:true,opacity:blocked&&!ok?.45:.75,depthWrite:false})); m.scale.setScalar(.8); m.position.set(e.out[0],.05,e.out[1]); m.renderOrder=6; entryMarks.add(m); } }
const arc=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:0xff7a4a,dashSize:.25,gapSize:.15})); arc.visible=false; scene.add(arc);
function arcPoints(a,b,n){ const pts=[], y0=yOf(...a)+1.5, y1=yOf(...b)+.1, L=Math.hypot(b[0]-a[0],b[1]-a[1]); for(let k=0;k<=n;k++){ const t=k/n; pts.push(new THREE.Vector3(a[0]+(b[0]-a[0])*t,y0+(y1-y0)*t+Math.sin(t*Math.PI)*Math.max(1.2,L*.28),a[1]+(b[1]-a[1])*t)); } return pts; }
const blastFx=[];

// ---------- orders ----------
// u.order = {move:{p,cost,path}, act:{type,...}, free:{target}, rungun}
//   act types: shoot, pistol (Sharpshooter), slash (Ranger), throw (Breacher), aid (Medic), charge (Breacher, a wall),
//   flip, close, search, evac, ow, hunker, reload
const orderOf=u=>u.order||(u.order={move:null,act:null,free:null,rungun:false});
const planned=u=>u.order&&u.order.move?u.order.move.p:P(u);
const ghostAt=u=>{ const p=planned(u); return Object.assign({},u,{x:p[0],z:p[1]}); };
const apTotal=u=>2+(u.order&&u.order.rungun?1:0);
const moveAP=u=>{ const m=u.order&&u.order.move; if(!m) return 0; return m.cost<=(u.move||CR.V.move)?1:2; };
function moveBudget(u){ const mv=u.move||CR.V.move, act=u.order&&u.order.act&&u.order.act.type!=='slash'?1:0, ap=Math.min(2,apTotal(u)-act); return ap>=2?2*mv:ap>=1?mv:0; }
const ACT_LABEL={shove:'shove clear',drag:'drag',shoot:'shoot',pistol:'revolver',slash:'slash',throw:'pipe bomb',aid:'first aid',charge:'charge',flip:'overturn',close:'close door',search:'take stash',evac:'get out',ow:'overwatch',hunker:'hunker',reload:'reload'};
function orderText(u){ const o=u.order; if(!o||(!o.move&&!o.act&&!o.free)) return 'no orders: holds'; const parts=[];
  if(o.free) parts.push('free shot → '+o.free.target.name);
  if(o.move) parts.push((o.move.cost<=(u.move||CR.V.move)?'move ':'dash ')+o.move.cost.toFixed(0)+' m');
  if(o.act){ const a=o.act; parts.push(ACT_LABEL[a.type]+(a.target&&a.target!==u?' → '+a.target.name+(a.odds?' '+a.odds.aim+'%':''):'')); }
  if(o.rungun) parts.push('run & gun'); return parts.join(' · '); }
function setMove(u,p,cost,path){ const o=orderOf(u), mv=u.move||CR.V.move;
  if(o.act&&o.act.type==='slash') o.act=null;
  if(cost>mv&&o.act&&apTotal(u)<3){ log(`${u.name}: a dash leaves no time for the ${ACT_LABEL[o.act.type]}.`); o.act=null; }
  o.move={p,cost,path}; if(o.act&&o.act.target&&o.act.weapon) o.act.odds=previewOdds(u,o.act.target,o.act.weapon); }
function setAct(u,act){ const o=orderOf(u); if(act.type!=='slash'&&moveAP(u)>=2&&apTotal(u)<3){ o.move=null; log(`${u.name} will not dash, to keep an action for the ${ACT_LABEL[act.type]}.`); }
  if(act.type==='slash') o.move=null; o.act=act; }
function previewOdds(u,t,W){ const g=ghostAt(u); const lf=CR.lineOfFire(S.w,g,t,{pierce:true}); if(!lf) return null; return CR.odds(S.w,g,t,{weapon:W||u.weapon,walls:lf.walls,steady:u.role==='sharpshooter'&&!(u.order&&u.order.move)&&(W||u.weapon)===u.weapon}); }
// draw every soldier's orders: where they will stand, how they get there, and what they will do
function drawOrders(){ while(orderViz.children.length){ const m=orderViz.children.pop(); if(m.geometry&&m.geometry!==ringG) m.geometry.dispose(); }
  if(S.phase!=='plan') return;
  squad().forEach((u,i)=>{ if(!u.alive||u.evac) return; const o=u.order; if(!o) return; const c=SQUAD_COL[i%4];
    if(o.move){ const g=new THREE.Mesh(ringG,new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:S.sel===u?.95:.6,depthWrite:false})); g.position.set(o.move.p[0],yOf(...o.move.p)+.06,o.move.p[1]); g.renderOrder=6; orderViz.add(g);
      const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints(o.move.path.points.map(q=>new THREE.Vector3(q.x,yOf(q.x,q.z)+.1,q.z))),new THREE.LineDashedMaterial({color:c,dashSize:.3,gapSize:.15,transparent:true,opacity:S.sel===u?1:.6})); l.computeLineDistances(); orderViz.add(l); }
    const from=planned(u), line=(t,colr)=>{ const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(from[0],yOf(...from)+1.3,from[1]),new THREE.Vector3(t[0],yOf(...t)+1.2,t[1])]),new THREE.LineDashedMaterial({color:colr,dashSize:.35,gapSize:.2})); l.computeLineDistances(); orderViz.add(l); };
    if(o.free) line(P(o.free.target),0xffe3a0);
    if(o.act&&o.act.target&&o.act.target!==u) line(P(o.act.target),o.act.type==='aid'?0x3fdc8f:0xff6a4a);
    if(o.act&&o.act.point) line(o.act.point,0xff7a4a); }); }

// ---------- vision: what the squad sees is all you see ----------
function seenBySquad(r){ for(const u of squad()) if(u.alive&&!u.evac&&CR.dist(u,r)<=CR.V.spot&&CR.lineOfFire(S.w,u,r,{shot:false})) return true; return false; }
function updateVision(dt){ for(const r of S.units){ if(r.team!=='raider') continue; if(r.revealT>0) r.revealT-=dt;
    let v; if(r.alive) v=seenBySquad(r)||r.revealT>0; else v=!!(r.vis||r.seenDead);
    if(!r.alive&&v) r.seenDead=true; if(v&&r.alive){ r.seen=true; r.last=[r.x,r.z]; }
    if(v!==r.vis){ r.vis=v; r.fig.root.visible=v&&!r.fled; } } }

// ---------- badges: hit chances, planned shots and where unseen raiders were last seen ----------
let hoverSpot=null;
const tmpV=new THREE.Vector3();
function screenOf(x,y,z){ const st=$('stage'), W=st.clientWidth, H=st.clientHeight; tmpV.set(x,y,z).project(camera); if(tmpV.z>1) return null; return [((tmpV.x+1)/2*W),((1-tmpV.y)/2*H)]; }
function drawBadges(){ const out=[], u=S.sel, M=S.mission, put=(x,y,z,cls,txt)=>{ const s=screenOf(x,y,z); if(s) out.push(`<span class="badge ${cls}" style="left:${s[0].toFixed(0)}px;top:${s[1].toFixed(0)}px">${txt}</span>`); };
  const plan=S.phase==='plan'&&u&&u.alive&&u.team==='squad';
  for(const t of S.units){ if(t.team!=='raider'||!t.alive||t.fled) continue;
    if(!t.vis){ if(t.last&&S.phase!=='explore') put(t.last[0],yOf(...t.last)+.9,t.last[1],'ghost','last seen ?'); continue; }
    let txt='', cls='';
    if(plan){ const shots=squad().filter(v=>v.alive&&v.order&&((v.order.act&&v.order.act.target===t&&/shoot|pistol|slash/.test(v.order.act.type))||(v.order.free&&v.order.free.target===t)));
      if(hoverSpot){ if(S.w.coverFrom(P(t),hoverSpot)===0&&S.w.sight(hoverSpot,P(t),{shot:true})){ txt='FLANK'; cls='flank'; } }
      else { const o=previewOdds(u,t); if(o){ txt=o.aim+'%'+(o.flanked?' · FLANKED':''); if(o.flanked) cls='flank'; } }
      if(shots.length){ txt+=(txt?' · ':'')+`${shots.length} on them · ${t.hp} HP`; cls=shots.length>1?'over':'plan'; } }
    else if(t.unaware) txt='?';
    if(t.armor) txt+=(txt?' ':'')+'<span class="arm">'+'◆'.repeat(t.armor)+'</span>';
    if(txt) put(t.x,yOf(t.x,t.z)+2.15,t.z,cls,txt); }
  if(S.phase==='plan') for(const v of squad()) if(v.alive&&v.order&&(v.order.move||v.order.act)){ const p=planned(v); put(p[0],yOf(...p)+.55,p[1],'plan',v.name+(v.order.act?' · '+ACT_LABEL[v.order.act.type]:'')); }
  if(M&&M.stash&&!M.stashTaken&&S.phase!=='over') put(M.stash[0],yOf(...M.stash)+1.4,M.stash[1],'loot','Stash');
  if(M&&M.stashTaken&&S.phase!=='over') put(M.evac[0],.6,M.evac[1],'evac','Way out');
  if(S.G.test&&S.labels) for(const L of S.G.test.labels) put(L.p[0],.3,L.p[1],'zone',L.text);
  badgesEl.innerHTML=out.join(''); }

// ---------- figures (the shared motion module poses them) ----------
function makeFig(seed,fem,ink,kind){ const f=FigureKit.figure(fem,FigureKit.genFace(seed,fem)); f.ink=FigureKit.inkUp(f.root,{persp:true,width:.0016,color:ink}); f.root.traverse(o=>{ if(o.isMesh) o.castShadow=true; });
  if(kind) f.gun=Motion.arm(f,kind,{ink:{persp:true,width:.0016}}); scene.add(f.root); return f; }
const gunKind=W=>W.melee?null:(W.ammo===Infinity||/Pistol|Revolver/.test(W.name))?'pistol':'rifle';
function ink(u){ if(!u.fig) return; const k=u.dead?'dead':u.down?'wounded':!u.alive?'dead':u.team==='raider'?(u.fleeing?'panicked':'raider'):S.phase==='explore'?(S.sel===u?'selected':'concealed'):u.ow?'overwatch':u.hp<=u.max/2?'wounded':S.sel===u?'selected':'calm'; u.fig.ink.color.setHex(INKS[k]); }
const inkAll=()=>S.units.forEach(ink);

// ---------- popups, tracers, log ----------
const pops=[], tracers=[], waits=[];
const wait=ms=>new Promise(r=>waits.push({t:ms,r}));
function pop(u,text,cls){ const el=document.createElement('div'); el.className='pop '+(cls||''); el.textContent=text; $('stage').appendChild(el); const x=u.x!=null?u.x:u[0], z=u.z!=null?u.z:u[1]; pops.push({el,x,y:yOf(x,z)+2.2+pops.filter(p=>p.t<.3).length*.35,z,t:0}); }
function tracer(a,b,hit,r){ const off=hit?0:(r()-.5)*1.6; const g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(a[0],yOf(...a)+1.35,a[1]),new THREE.Vector3(b[0]+off,yOf(...b)+(hit?1.2:1.7),b[1]-off)]);
  const l=new THREE.Line(g,new THREE.LineBasicMaterial({color:0xffe3a0,transparent:true})); scene.add(l); tracers.push({l,t:0}); }
function log(t){ const p=document.createElement('p'); p.textContent=t; logEl.prepend(p); while(logEl.children.length>60) logEl.lastChild.remove(); }
window.__combatNote=t=>{ if(t&&!/^Click|^Overturned/.test(t)) log(t); };
function flash(title,text,ours,keep){ bannerEl.className='banner'+(ours?' ours':''); bannerEl.innerHTML=`<b>${title}</b>${text}`; bannerEl.hidden=false; clearTimeout(flash.t); if(!keep) flash.t=setTimeout(()=>{ if(!S.prompt) bannerEl.hidden=true; },3800); }
const clock=()=>{ const m=S.minutes%(24*60); return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0'); };

// ---------- setting up a fight ----------
function setup(){
  const test=$('bSel').value==='test', site=test?null:SITES[+$('bSel').value], hist=test?'den':$('hSel').value, seedStr=test?'test/range':site.id+(S.seed?'#'+S.seed:'');
  for(const u of S.units) if(u.fig) scene.remove(u.fig.root);
  closeMenu();
  const g=test?CombatTestMap.build({prepFootprint,streetSense,R,IT,edgeKey,DIRS,styleFor,rngOf,setLevel,noise2,TYPES,WALLMAT}):generate(site,'auto',seedStr,hist); const rec={doors:{},taken:[],moved:{},windows:{},blasts:[],walls:{}}; const w=InteriorSpace.fromGenerated(g,{doors:rec.doors,walls:rec.walls});
  G=g; REC=rec;   // the interiors physics code works on these page globals
  Object.assign(S,{G:g,w,rec,units:[],phase:'explore',round:1,minutes:14*60,busy:false,free:false,slow:1,mode:'move',prompt:false,declined:new Set(),rng:CR.rng(seedStr+'|fight'),destroyed:new Set(),stats:{shots:0,hits:0,bombs:0,wasted:0}});
  logEl.innerHTML=''; bannerEl.hidden=true;
  rebuild();
  const ppl=g.test?g.test.posts.map(q=>({p:q.p.slice(),boss:q.boss,role:q.post,face:q.face,type:q.type,side:'raider'})):w.posted(seedStr), tr=CR.rng(seedStr+'|types'), pool=['brute','enforcer','raider','raider','brute','raider'];
  let k=Math.floor(tr()*2);
  ppl.forEach((p,i)=>{ const type=p.type||(p.boss?'boss':p.role==='sentry'?'raider':pool[(k++)%pool.length]), label=type==='boss'?(p.side==='raider'?'Raider boss':'Holdout leader'):p.role==='sentry'?'Sentry':CR.ROLES[type].label;
    const u=CR.makeUnit(type,{id:'r'+i,team:'raider',boss:p.boss,name:label,x:p.p[0],z:p.p[1],ap:0,unaware:true,face:p.face,post:p.role,look:p.face,lookT:0,vis:true});
    u.fig=makeFig(4000+i*13+S.seed*7,i%2===1,INKS.raider,gunKind(u.weapon)); S.units.push(u); });
  const camp=S.units.filter(u=>u.post==='camp'&&u.role!=='brute'); if(camp.length&&!g.test) setPatrol(camp[0]);
  const fa=w.frontApproach(); const start=fa?fa.out:[w.X0+14,w.Z0+14]; const nrm=fa?[fa.out[0]-fa.in[0],fa.out[1]-fa.in[1]]:[0,1], L=Math.hypot(...nrm); const n=[nrm[0]/L,nrm[1]/L], t=[-n[1],n[0]];
  const spots=[]; const ok=q=>w.clearAt(q[0],q[1],w.R+.1)&&!w.insideAt(q[0],q[1])&&!spots.some(s=>Math.hypot(s[0]-q[0],s[1]-q[1])<1.1)&&!S.units.some(r=>CR.sees(w,r,q));
  for(let d=6;d<30&&spots.length<4;d+=.5) for(const s of [0,1.2,-1.2,2.4,-2.4,3.6,-3.6]){ const q=[start[0]+n[0]*d+t[0]*s,start[1]+n[1]*d+t[1]*s]; if(spots.length<4&&ok(q)) spots.push(q); }
  for(let d=6;spots.length<4&&d<30;d+=.5) for(let a=0;a<12&&spots.length<4;a++){ const q=[start[0]+Math.sin(a)*d,start[1]+Math.cos(a)*d]; if(w.clearAt(q[0],q[1],w.R+.1)&&!w.insideAt(...q)&&!spots.some(s=>Math.hypot(s[0]-q[0],s[1]-q[1])<1.1)) spots.push(q); }
  S.roster.squad.forEach((m,i)=>{ const q=spots[i]; const u=CR.makeUnit(m.role,{id:'s'+i,team:'squad',name:m.name,nick:m.nick,rank:CR.rankOf(m.xp),member:m,kills:0,x:q[0],z:q[1],face:Math.atan2(-n[0],-n[1])});
    u.fig=makeFig(900+i*31+(m.seed||0),i%2===0,INKS.concealed,gunKind(u.weapon)); S.units.push(u); });
  const items=g.Fn.items.filter(it=>it.spec.slot&&it.contents&&it.contents.length); let stash=items.filter(it=>it.stash)[0];
  const boss=S.units.find(u=>u.boss); if(!stash&&boss) stash=items.slice().sort((a,b)=>dist2(a,boss)-dist2(b,boss))[0]; if(!stash) stash=items[0];
  const so=stash&&w.obs.find(o=>o.kind==='item'&&o.it===stash);
  S.mission={stashItem:stash,stash:so?[(so.box.x0+so.box.x1)/2,(so.box.z0+so.box.z1)/2]:null,stashTaken:false,evac:[start[0]+n[0]*9,start[1]+n[1]*9],evacR:2.4,reinforceIn:null,evacuated:[]};
  S.sel=S.units.find(u=>u.team==='squad'); view.target.set(S.sel.x,0,S.sel.z); view.az=Math.atan2(n[0],n[1]);
  updateVision(0); inkAll(); select(S.sel); drawHud(); drawEntries(); drawEvac();
  log(g.test?'Test range: every wall build-up, window sill, door, counter and kind of cover, and every enemy type. Labels: the Labels button.':`${g.label}, ${hist==='den'?'raider den':'holdout'}. Generated in ${g.ms|0} ms.`);
  flash('Concealed','You only see what your squad sees. Walk in real time (left click); spot one of them first and you choose: strike first or hold back. Gold rings are doors, blue rings windows: right click one to stack there, then breach. In a fight, give everyone orders (left click: move, right click: what to do), then Go: the whole squad moves at once.',true);
}
const dist2=(it,u)=>{ const c=it.cells[0], M=S.G.M; return Math.hypot(M.u0+(c%M.W)+.5-u.x,M.v0+((c/M.W)|0)+.5-u.z); };
function setPatrol(u){ const w=S.w, M=S.G.M, F=w.field(P(u),300,[]), stops=[];
  for(const r of S.G.P.rooms){ if(r.cells.length<6) continue; let a=0,b=0; for(const c of r.cells){ a+=c%M.W; b+=(c/M.W)|0; } const q=w.snap([M.u0+a/r.cells.length+.5,M.v0+b/r.cells.length+.5],.01); const c=w.costTo(F,q); if(c&&!c.over&&c.cost<60) stops.push({q,c:c.cost}); }
  stops.sort((a,b)=>a.c-b.c); const pts=[P(u)].concat(stops.slice(0,3).map(s=>s.q)); if(pts.length<2) return; u.patrol={pts,k:1,pause:0}; u.post='patrol'; }
function rebuild(){ const items=S.destroyed.size?S.G.Fn.items.map(it=>S.destroyed.has(it.id)?Object.assign({},it,{spec:IT.debris}):it):S.G.Fn.items;
  build(Object.assign({},S.G,{D:{people:[]},Fn:Object.assign({},S.G.Fn,{items})}),S.rec); dirtyBuild=false;
  world.traverse(o=>{ if(o.isMesh&&o.material&&o.material.isMeshBasicMaterial&&o.material.vertexColors&&o.material.transparent&&o.material.opacity===.55) o.visible=false; }); }
window.__combatRefresh=()=>{ rebuild(); if(S.w){ const a=S.w.syncMoves(S.rec), b=S.w.syncWalls(); if((a||b)&&planning()){ drawReach(); drawSight(); } } };

// ---------- selection and the bar ----------
const others=except=>S.units.filter(u=>u.alive&&u!==except).map(P).concat(S.units.filter(u=>u.down&&!u.dead).map(P));
function select(u){ if(!u||!u.alive||u.evac) return; S.sel=u; S.mode='move'; closeMenu(); arc.visible=false; inkAll(); S.camGoal={x:u.x,z:u.z}; drawReach(); drawSight(); drawOrders(); drawBar(); drawHud(); if(S.phase==='explore') drawEntries(); }
const squad=()=>S.units.filter(u=>u.team==='squad');
const standing=()=>squad().filter(u=>u.alive&&!u.evac);
function usable(e,u){ if(!S.w.clearAt(e.out[0],e.out[1])) return false; if(e.kind==='window'&&(e.e.win.sill==null?.9:e.e.win.sill)>1.3) return false; if(S.w.props(e.o).cross&&e.kind!=='garage') return true; return !!(u&&u.role==='breacher'&&u.kit.charge>0&&(e.kind!=='garage')); }
const entryAt=u=>S.w.entries().find(e=>Math.hypot(e.out[0]-u.x,e.out[1]-u.z)<1.1&&usable(e,u)&&!squad().some(v=>v!==u&&v.stack===e));
const itemName=k=>k.replace(/\d+$/,'').replace(/([a-z])([A-Z])/g,'$1 $2').toLowerCase();
const boxDist=(b,x,z)=>Math.hypot(Math.max(b.x0-x,0,x-b.x1),Math.max(b.z0-z,0,z-b.z1));
function unitLabel(v){ if(v.evac) return 'out'; if(v.dead) return 'dead'; if(v.down) return v.stable?'down · stable':`bleeding · ${v.bleed}`; return S.phase==='explore'?(v.stack?'stacked':'ready'):''; }
function drawBar(){ const u=S.sel;
  unitsEl.innerHTML=squad().map(v=>{ const i=S.units.indexOf(v); return `<button type="button" class="unit${v.dead?' dead':v.down?' down':''}" data-i="${i}" aria-pressed="${S.sel===v}" ${v.alive&&!v.evac?'':'disabled'}>${v.name}${v.nick?' “'+v.nick+'”':''} <em>${rankName(v.member.xp)} ${roleOf(v).label}</em> ${unitLabel(v)} · ${v.ammo}/${v.weapon.ammo}${v.free?' · free shot':''}<i><s style="width:${v.hp/v.max*100}%;background:${v.hp<=v.max/2?'#c23b2e':'#3fae7f'}"></s></i>${S.phase==='plan'&&v.alive&&!v.evac?`<small>${orderText(v)}</small>`:''}</button>`; }).join('')+
    S.units.filter(v=>v.team==='raider'&&(v.vis||v.seen||!v.alive&&v.seenDead)).map(v=>`<span class="unit foe${v.alive?'':' dead'}${v.fleeing&&v.alive?' flee':''}">${v.name}${v.armor?' ◆'.repeat(v.armor):''}${v.fled?' · fled':!v.alive?' · down':!v.vis?' · out of sight':v.fleeing?' · running':v.unaware?' · unaware':''}<i><s style="width:${v.hp/v.max*100}%;background:#c23b2e"></s></i></span>`).join('');
  if(S.phase==='over'){ actsEl.innerHTML='<button type="button" class="pri" data-a="restart">Again</button><button type="button" data-a="reroll">Another layout</button>'; return; }
  if(S.prompt){ actsEl.innerHTML='<span class="hint">Contact: choose above</span>'; return; }
  if(S.phase==='exec'||S.phase==='raiders'||S.phase==='breach'){ actsEl.innerHTML=`<span class="hint" style="color:${S.phase==='raiders'?'#e2b0a8':'#f3d38a'}">${S.phase==='breach'?'Breaching…':S.phase==='raiders'?'Raiders act…':'Your squad moves…'}</span>`; return; }
  if(S.mode==='drag'&&u){ actsEl.innerHTML=`<span class="hint">Click the floor where ${u.name} drags it (up to 8 m)</span><button type="button" data-a="back">Back</button>`; return; }
  if(S.mode==='throw'&&u){ actsEl.innerHTML=`<span class="hint">Click where ${u.name}'s pipe bomb lands (${CR.V.throwRange} m from where they will stand)</span><button type="button" data-a="back">Back</button>`; return; }
  const mine=!S.busy&&u&&u.alive&&u.team==='squad';
  if(S.phase==='explore'){ const e=mine&&(u.stack||entryAt(u)), stacked=squad().filter(v=>v.alive&&v.stack), anyLine=mine&&S.units.some(t=>t.team==='raider'&&t.alive&&t.vis);
    const blown=e&&!S.w.props(e.o).cross;
    actsEl.innerHTML=(nearStash(u)?'<button type="button" class="pri" data-a="search">Take the stash</button>':'')+(e?`<button type="button" data-a="stack" aria-pressed="${!!u.stack}">${u.stack?'Unstack':(blown?'Set charge on ':'Stack at ')+(e.kind==='window'?'window':e.role==='front'?'front door':e.role==='back'?'back door':'side door')}</button>`:'')+
      `<button type="button" class="pri" data-a="breach" ${stacked.length&&!S.busy?'':'disabled'}>Breach${stacked.length?' ('+stacked.length+')':''} [B]</button><button type="button" data-a="fire" ${anyLine?'':'disabled'}>Open fire</button><button type="button" data-a="wait" ${S.busy?'disabled':''}>Wait</button>`; return; }
  const n=standing().filter(v=>v.order&&(v.order.move||v.order.act||v.order.free)).length;
  actsEl.innerHTML=`<span class="hint">Left click: move · click a raider, or right click a thing or ${u?u.name:'a soldier'}: what to do · WASD: camera</span><button type="button" data-a="clear" ${u&&u.order?'':'disabled'}>Clear ${u?u.name+"'s":''} orders [⌫]</button><button type="button" class="pri" data-a="go">Go: ${n} of ${standing().length} with orders [Space]</button>`; }
function drawHud(){ const left=S.units.filter(u=>u.team==='raider'&&u.alive&&u.vis).length, M=S.mission;
  const obj=!M?'':M.stashTaken?`Stash taken: get everyone to the way out (${M.evacuated.length} out)`:M.stash?'Objective: take the stash, or clear the building':'Objective: clear the building';
  const rf=M&&M.reinforceIn!=null&&M.reinforceIn>0?` · <span style="color:#e2b0a8">reinforcements in ${M.reinforceIn}</span>`:'';
  const ph={explore:'Concealed',plan:'Orders',exec:'Go',raiders:'Raiders',breach:'Breach',over:'Over'}[S.phase];
  hudEl.innerHTML=`<b>${ph}</b>${clock()} · ${S.phase==='explore'?'exploring':'round '+S.round} · ${left} in sight${rf}<div class="sub">${obj}</div><div class="sub">${S.G.label} · ${S.w.G.site.id}</div>`+
    (S.sel&&S.sel.team==='squad'?`<div class="sub">${S.sel.name}: ${S.sel.weapon.name} (${S.sel.weapon.profile} range)${S.sel.second?' + '+S.sel.second.name:''} · ${roleOf(S.sel).skill}</div>`:''); }
function whyHtml(o,W){ return '<div class="why">'+o.why.map(([k,v],i)=>`<span>${k}</span><span class="${i===0?'':v<0?'neg':'pos'}">${i===0?v:(v>0?'+':'')+v}</span>`).join('')+`<b>Hit</b><b>${o.aim}%</b><span>Crit</span><span>${o.crit}%</span><span>Damage</span><span>${W.dmg[0]}–${W.dmg[1]}</span></div>`; }

// ---------- the right-click menu ----------
function closeMenu(){ ctxEl.hidden=true; ctxEl.innerHTML=''; ctxEl.items=null; }
function openMenu(ev,title,items,note){ if(!items.length) return; const st=$('stage').getBoundingClientRect();
  ctxEl.innerHTML=`<h3>${title}</h3>`+items.map((it,i)=>`<button type="button" role="menuitem" data-k="${i}" ${it.off?'disabled':''}>${it.label}<span>${it.off?it.off:it.sub||''}</span></button>`).join('')+(note?`<p>${note}</p>`:'');
  ctxEl.items=items; ctxEl.hidden=false; const x=Math.min(ev.clientX-st.left,st.width-ctxEl.offsetWidth-8), y=Math.min(ev.clientY-st.top,st.height-ctxEl.offsetHeight-8); ctxEl.style.left=Math.max(8,x)+'px'; ctxEl.style.top=Math.max(8,y)+'px';
  const b=ctxEl.querySelector('button:not(:disabled)'); if(b) b.focus(); }
ctxEl.addEventListener('click',e=>{ const b=e.target.closest('button[data-k]'); if(!b||b.disabled) return; const it=ctxEl.items[+b.dataset.k]; closeMenu(); hoverEl.textContent=''; it.fn(); });
ctxEl.addEventListener('pointerover',e=>{ const b=e.target.closest('button[data-k]'); const it=b&&ctxEl.items&&ctxEl.items[+b.dataset.k]; hoverEl.innerHTML=it&&it.why?it.why:''; });
ctxEl.addEventListener('contextmenu',e=>e.preventDefault());
addEventListener('pointerdown',e=>{ if(!ctxEl.hidden&&!ctxEl.contains(e.target)) closeMenu(); },true);
// where a soldier could stand next to something to work on it, reachable this round with an action to spare
function standBeside(u,box,maxCost){ const F=S.F; if(!F) return null; let best=null; const cx=(box.x0+box.x1)/2, cz=(box.z0+box.z1)/2;
  for(let k=0;k<16;k++){ const a=k/16*Math.PI*2, r=Math.max(box.x1-box.x0,box.z1-box.z0)/2+.55, q=[cx+Math.sin(a)*r,cz+Math.cos(a)*r]; if(!S.w.clearAt(...q)) continue;
    if(boxDist(box,q[0],q[1])>.95) continue; const c=Math.hypot(q[0]-u.x,q[1]-u.z)<.3?{cost:0}:S.w.costTo(F,q); if(!c||c.over||c.cost>maxCost) continue; if(!best||c.cost<best.cost) best={p:q,cost:c.cost}; }
  if(best&&best.cost>0){ best.path=S.w.pathTo(F,best.p); if(!best.path) return null; } return best; }
function moveFor(u,spot){ if(spot&&spot.cost>0) setMove(u,spot.p,spot.cost,spot.path); else if(spot) orderOf(u).move=null; }
const besideBudget=u=>(u.move||CR.V.move)*(apTotal(u)-1);
function rightClick(ev,p,hit){ const u=S.sel; if(!u||!u.alive) return; if(hit&&!p) p=[hit.x,hit.z]; if(!p) return;
  const near=(x,z,r)=>Math.hypot(x-p[0],z-p[1])<r;
  if(hit===undefined) hit=S.units.find(v=>v.team==='raider'&&v.alive&&v.vis&&near(v.x,v.z,.75))||S.units.find(v=>v.team==='squad'&&(v.alive||v.down&&!v.dead)&&!v.evac&&near(...planned(v),.6));
  const t=hit&&hit.team==='raider'&&hit.alive&&hit.vis?hit:null;
  if(S.phase==='explore'){
    if(t) openMenu(ev,t.name,[{label:'Engage: first strike',sub:'everyone',fn:()=>startFight('squad','The squad opens fire.')}],'They have not seen you.');
    else if(hit&&hit.team==='squad'&&hit.alive) select(hit);
    else { const e=S.w.entries().find(x=>near(x.out[0],x.out[1],.9)&&usable(x,u)); if(e) openMenu(ev,e.kind==='window'?'Window':(e.role||'side')+' door',[{label:!S.w.props(e.o).cross?'Set charge here':'Stack here',sub:u.name,fn:async()=>{ const path=S.F&&S.w.pathTo(S.F,e.out); S.busy=true; await walk(u,path?path.points:[{x:u.x,z:u.z},{x:e.out[0],z:e.out[1]}]); if(S.phase!=='explore') return; S.busy=false; u.stack=e; u.face=Math.atan2(e.in[0]-e.out[0],e.in[1]-e.out[1]); drawReach(); drawBar(); }}]); }
    return; }
  if(!planning()){ if(S.phase==='exec'||S.phase==='raiders') log('Orders are given between rounds.'); return; } const items=[], g=ghostAt(u), o=orderOf(u);
  // raiders: what this soldier can do to them, with odds from where the soldier will stand
  if(t){ const lf=CR.lineOfFire(S.w,g,t,{pierce:true});
    if(u.free){ const lf0=CR.lineOfFire(S.w,u,t,{pierce:true}), fo=lf0&&CR.odds(S.w,u,t,{free:true,walls:lf0.walls,mod:u.entryMod||0,modLabel:'Through a window'}); items.push({label:'Free shot',sub:fo?fo.aim+'%':'',off:lf0?null:'no line',why:fo&&whyHtml(fo,u.weapon),fn:()=>{ o.free={target:t}; afterOrder(u); }}); }
    const od=previewOdds(u,t); items.push({label:'Shoot'+(lf&&lf.walls?' through the wall':''),sub:od?od.aim+'% · '+u.weapon.dmg.join('–'):'',off:u.ammo<=0?'empty':!lf?'no line from there':null,why:od&&whyHtml(od,u.weapon),fn:()=>{ setAct(u,{type:'shoot',target:t,weapon:u.weapon,odds:previewOdds(u,t)}); afterOrder(u); }});
    if(u.second&&!u.second.melee){ const o2=previewOdds(u,t,u.second); items.push({label:u.second.name,sub:o2?o2.aim+'% · no reload':'',off:!lf?'no line from there':null,why:o2&&whyHtml(o2,u.second),fn:()=>{ setAct(u,{type:'pistol',target:t,weapon:u.second,odds:previewOdds(u,t,u.second)}); afterOrder(u); }}); }
    if(u.second&&u.second.melee){ const F=S.w.field(P(u),(u.move||CR.V.move)*2,others(u)), spot=CR.meleeSpot(S.w,F,u,t,S.units), om=CR.odds(S.w,u,t,{weapon:u.second}); items.push({label:'Slash',sub:om.aim+'% · run in',off:spot?null:'too far to reach',why:whyHtml(om,u.second),fn:()=>{ setAct(u,{type:'slash',target:t,weapon:u.second,odds:om}); afterOrder(u); }}); }
    if(u.role==='breacher'){ const q=landing(g,P(t)); items.push({label:'Pipe bomb on them',sub:'×'+u.kit.pipe,off:u.kit.pipe<=0?'none left':!q?'no clear throw':null,fn:()=>{ setAct(u,{type:'throw',point:q}); afterOrder(u); }}); }
    openMenu(ev,`${u.name} → ${t.name} (${t.hp} HP${t.armor?', armour '+t.armor:''})`,items,'Odds are from where '+u.name+' will stand. Others ordered onto them may leave nothing to hit.'); return; }
  // a soldier: the selected one's own actions, or first aid for someone else
  const ally=hit&&hit.team==='squad'&&(hit.alive||hit.down&&!hit.dead)&&!hit.evac?hit:null;
  if(ally&&ally===u){ items.push({label:'Overwatch',sub:'react to movement',off:u.ammo<=0?'empty':null,fn:()=>{ setAct(u,{type:'ow'}); afterOrder(u); }},{label:'Hunker down',sub:'cover counts more',fn:()=>{ setAct(u,{type:'hunker'}); afterOrder(u); }},{label:'Reload',sub:u.ammo+'/'+u.weapon.ammo,off:u.ammo>=u.weapon.ammo?'full':null,fn:()=>{ setAct(u,{type:'reload'}); afterOrder(u); }});
    if(u.role==='ranger') items.push({label:o.rungun?'Cancel run and gun':'Run and gun',sub:'+1 action',off:u.cooldown?'ready in '+u.cooldown:null,fn:()=>{ o.rungun=!o.rungun; afterOrder(u); }});
    if(u.role==='medic'&&u.hp<u.max) items.push({label:'First aid: self',sub:'+'+CR.V.aidHeal,off:u.kit.aid<=0?'none left':null,fn:()=>{ setAct(u,{type:'aid',target:u}); afterOrder(u); }});
    if(u.role==='breacher') items.push({label:'Throw a pipe bomb…',sub:'×'+u.kit.pipe,off:u.kit.pipe<=0?'none left':null,fn:()=>{ S.mode='throw'; clearReach(); drawBar(); }});
    items.push({label:'Hold: clear orders',sub:'',fn:()=>{ u.order=null; afterOrder(u); }}); openMenu(ev,u.name,items); return; }
  if(ally&&u.role==='medic'){ const ap=planned(ally), box={x0:ap[0]-.3,x1:ap[0]+.3,z0:ap[1]-.3,z1:ap[1]+.3}, spot=standBeside(u,box,besideBudget(u));
    items.push({label:ally.down?(ally.stable?'Get them up':'Stabilise'):'First aid',sub:ally.down?'':'+'+CR.V.aidHeal+' HP',off:u.kit.aid<=0?'none left':!spot?'too far':null,fn:()=>{ moveFor(u,spot); setAct(u,{type:'aid',target:ally}); afterOrder(u); }}); openMenu(ev,ally.name,items); return; }
  // things: the stash, furniture to tip over, a door to shut, a wall to blow
  const M=S.mission;
  if(M&&M.stash&&!M.stashTaken){ const so=S.w.obs.find(x=>x.kind==='item'&&x.it===M.stashItem); if(so&&boxDist(so.box,p[0],p[1])<.4){ const spot=standBeside(u,so.box,besideBudget(u)); items.push({label:'Take the stash',sub:'',off:spot?null:'too far',fn:()=>{ moveFor(u,spot); setAct(u,{type:'search'}); afterOrder(u); }}); openMenu(ev,'Stash',items); return; } }
  const it=S.w.obs.find(x=>x.kind==='item'&&!x.destroyed&&!x.flat&&boxDist(x.box,p[0],p[1])<.15);
  if(it&&typeof movable==='function'&&movable(it.it)){ const spot=standBeside(u,it.box,besideBudget(u));
    items.push({label:'Shove it clear',sub:'off doorways, to a wall',off:spot?null:'too far',fn:()=>{ moveFor(u,spot); setAct(u,{type:'shove',item:it}); afterOrder(u); }},
      {label:'Drag it to…',sub:'up to 8 m',off:spot?null:'too far',fn:()=>{ moveFor(u,spot); S.mode='drag'; S.dragItem=it; clearReach(); drawBar(); log('Click the floor where '+u.name+' drags the '+itemName(it.it.key)+'.'); }}); }
  if(it&&typeof FLIP_PROPS!=='undefined'&&FLIP_PROPS.has(it.it.key)&&!it.mv){ const spot=standBeside(u,it.box,besideBudget(u)); items.push({label:'Overturn for cover',sub:'tips away from '+u.name,off:spot?null:'too far',fn:()=>{ moveFor(u,spot); setAct(u,{type:'flip',item:it}); afterOrder(u); }}); }
  const edge=S.w.obs.find(x=>x.kind==='edge'&&SP.ptSeg(p[0],p[1],...x.seg).d<.35);
  if(edge&&/door/.test(edge.e.type)&&S.w.doorState(edge.e)==='open'){ const m=[(edge.seg[0]+edge.seg[2])/2,(edge.seg[1]+edge.seg[3])/2], spot=standBeside(u,{x0:m[0]-.5,x1:m[0]+.5,z0:m[1]-.5,z1:m[1]+.5},besideBudget(u)); items.push({label:'Close the door',sub:'blocks sight',off:spot?null:'too far',fn:()=>{ moveFor(u,spot); setAct(u,{type:'close',edge}); afterOrder(u); }}); }
  if(edge&&edge.e.type==='wall'&&u.role==='breacher'){ const dm=S.w.wallSt[S.w.LV+edge.e.key]; const m=SP.ptSeg(p[0],p[1],...edge.seg); const spot=standBeside(u,{x0:m.x-.45,x1:m.x+.45,z0:m.z-.45,z1:m.z+.45},besideBudget(u));
    items.push({label:'Set a breaching charge',sub:(edge.e.mat||'wall')+(dm&&dm.s?' · damaged':''),off:u.kit.charge<=0?'no charge left':dm&&dm.s>=3?'already open':!spot?'too far':null,fn:()=>{ moveFor(u,spot); setAct(u,{type:'charge',edge,at:[m.x,m.z]}); afterOrder(u); }}); }
  if(M&&M.stashTaken&&near(M.evac[0],M.evac[1],M.evacR)){ const c=S.F&&S.w.costTo(S.F,p); items.push({label:'Get out this way',sub:'',off:c&&!c.over?null:'too far',fn:()=>{ setMove(u,p,c.cost,S.w.pathTo(S.F,p)); setAct(u,{type:'evac'}); afterOrder(u); }}); }
  const tg=target(p), oneAct=(u.move||CR.V.move)*(apTotal(u)-1);
  if(tg){ items.push({label:'Move here, then overwatch',sub:tg.cost.toFixed(0)+' m',off:u.ammo<=0?'empty':tg.cost>oneAct?'needs a dash':null,fn:()=>{ setMove(u,tg.p,tg.cost,S.w.pathTo(S.F,tg.p)); setAct(u,{type:'ow'}); afterOrder(u); }},
    {label:'Move here, then hunker',sub:'',off:tg.cost>oneAct?'needs a dash':null,fn:()=>{ setMove(u,tg.p,tg.cost,S.w.pathTo(S.F,tg.p)); setAct(u,{type:'hunker'}); afterOrder(u); }}); }
  if(u.role==='breacher'){ const q=landing(g,p); items.push({label:'Pipe bomb here',sub:'×'+u.kit.pipe,off:u.kit.pipe<=0?'none left':!q?'no clear throw':null,fn:()=>{ setAct(u,{type:'throw',point:q}); afterOrder(u); }}); }
  const wname=e=>e.type==='wall'?(e.mat==='stud'?'Drywall':e.mat==='frame'?'Stucco wall':e.mat==='block'?'Block wall':e.mat==='vault'?'Concrete wall':'Wall'):e.type==='window'?'Window':'Door';
  openMenu(ev,edge&&edge.e.type==='wall'&&u.role==='breacher'?wname(edge.e):it?itemName(it.it.key):edge?wname(edge.e):'Here',items); }
function afterOrder(u){ drawReach(); drawOrders(); drawSight(); drawBar(); drawHud(); }

// ---------- doing things ----------
function walk(u,points){ return new Promise(res=>{ u.route=points.slice(1).map(q=>({x:q.x,z:q.z,through:q.through})); u.done=res; u.trav=0; }); }
function opening(u,o){ const e=o.e;
  if(/door/.test(e.type)&&S.w.doorState(e)==='closed'){ S.w.setDoor(e.key,'open'); dirtyBuild=true; noise(u,4,'door'); }
  if(e.type==='window'&&e.win.state==='intact'){ S.w.setWindow(e.key,'broken'); S.rec.windows[S.w.LV+e.key]=1; dirtyBuild=true; noise(u,14,'glass'); pop(u,'glass','info'); } }
function noise(u,radius,what){ if(S.phase!=='explore') return; const at=u.x!=null?P(u):u; for(const r of S.units) if(r.team==='raider'&&r.alive&&r.unaware){ const d=Math.hypot(r.x-at[0],r.z-at[1]), heard=S.w.sight(P(r),at)?radius:radius/2; if(d<=heard){ r.look=Math.atan2(at[0]-r.x,at[1]-r.z); r.lookT=6; if(r.vis) log(`${r.name} heard the ${what}.`); } } }
// exploring: one soldier walks where you click, in real time
async function walkTo(u,p){ const path=S.F&&S.w.pathTo(S.F,p); if(!path) return; S.busy=true; clearReach(); hideHover(); u.stack=null; await walk(u,path.points); if(S.phase!=='explore'||S.prompt) return; S.busy=false; if(dirtyBuild) rebuild(); drawReach(); drawBar(); drawEntries(); }
// one shot or swing at whoever is there now; a target already down means the shot goes nowhere
async function fireAt(a,b,W,opt={}){ if(!a.alive) return false;
  if(!b.alive){ if(a.team==='squad') S.stats.wasted++; log(`${a.name} has nothing to hit: ${b.name} is already down.`); pop(a,'no target','info'); return false; }
  const lf=W.melee?(CR.dist(a,b)<=CR.MELEE+.3?{from:P(a),to:P(b),walls:0}:null):CR.lineOfFire(S.w,a,b,{pierce:a.team==='squad'?!!b.vis:true});
  if(!lf){ log(`${a.name} has no line on ${b.name} from here.`); pop(a,'no line','info'); return false; }
  if(!W.melee&&W.ammo!==Infinity&&a.ammo<=0){ log(`${a.name} is out of ammunition.`); return false; }
  const o=opt.manual?null:CR.odds(S.w,a,b,Object.assign({},opt,{weapon:W,walls:lf.walls}));
  a.face=Math.atan2(b.x-a.x,b.z-a.z); a.aiming=true; if(a.team==='raider') a.revealT=1.6; await wait(W.melee?150:300);
  if(!b.alive){ a.aiming=false; if(a.team==='squad') S.stats.wasted++; log(`${a.name} lowers the ${W.name.toLowerCase()}: ${b.name} went down first.`); pop(a,'no target','info'); return false; }
  if(!W.melee&&W.ammo!==Infinity) a.ammo=Math.max(0,a.ammo-1);
  const res=opt.manual||CR.roll(o,S.rng,W,b);
  if(!W.melee){ tracer(lf.from,lf.to,res.hit,S.rng); Motion.kick(a.fig,'recoil'); } else pop(a,'slash','info');
  if(res.hit&&res.dmg) Motion.kick(b.fig,'hit',1,{from:{x:a.x,z:a.z}});
  if(a.team==='squad'){ S.stats.shots++; if(res.hit) S.stats.hits++; }
  if(!W.melee){ const crossed=[]; S.w.sight(lf.from,lf.to,{shot:true,collect:crossed}); for(const x of crossed) if(x.e&&x.e.type==='window'&&x.e.win.state==='intact'){ S.w.setWindow(x.e.key,'broken'); S.rec.windows[S.w.LV+x.e.key]=1; dirtyBuild=true; } }
  pop(b,res.blocked?'HIT COVER':res.hit?(res.head?`HEADSHOT −${res.dmg}`:res.crit?`CRIT −${res.dmg}`:res.dmg?`−${res.dmg}`:'ARMOR'):'Miss',res.hit?(res.crit||res.head?'crit':''):'miss');
  log(`${a.team==='raider'&&!a.vis?'Someone unseen':a.name} → ${b.team==='raider'&&!b.vis?'someone unseen':b.name}${W!==a.weapon?' ('+W.name.toLowerCase()+')':''}${lf.walls?' through the wall':''}: ${o?o.aim+'%':'aimed'}${opt.reaction?' (overwatch)':''}${opt.free?' (free)':''} · ${res.blocked?'hit cover':res.hit?(res.head?'headshot ':res.crit?'crit ':'hit ')+res.dmg+(res.armor?' ('+res.armor+' soaked)':''):'miss'}`);
  if(res.hit&&res.dmg) harm(b,res.dmg,a);
  if(!opt.free) b.unaware=false; ink(b); if(dirtyBuild) rebuild(); await wait(380); a.aiming=false; drawBar(); drawHud(); return res.hit; }
function harm(b,dmg,by){ const r=CR.hurt(b,dmg); if(r==='down'){ log(`${b.name} is down and bleeding: ${CR.V.bleed} turns to reach them.`); pop(b,'DOWN','crit'); } else if(r==='dead'){ log(`${b.name} is down.`); if(by&&by.team==='squad') by.kills=(by.kills||0)+1; } ink(b); }
async function overwatchCheck(m){ for(const w of S.units){ if(!w.alive||!w.ow||w.team===m.team||!m.alive||w.ammo<=0||w.evac) continue; if(CR.dist(w,m)>CR.V.overwatch||!CR.lineOfFire(S.w,w,m)) continue;
    const doorway=CR.atDoorway(S.w,P(m)); w.ow=false; ink(w); log(`${w.name} takes an overwatch shot${doorway?' at the doorway':''}.`); m.paused=true;
    if(w.team==='squad'&&S.fps&&!S.fpsBusy){ const r=await fpsShot(w,m,doorway); if(r){ await fireAt(w,m,w.weapon,{manual:r,reaction:true}); m.paused=false; continue; } }
    await fireAt(w,m,w.weapon,{reaction:true,doorway}); m.paused=false; } }

// ---------- first-person overwatch ----------
const fpsEl=$('fps'), fpsX=$('fpsX'), fpsBar=$('fpsBar'); let FP=null;
function fpsShot(w,m,doorway){ return new Promise(res=>{ S.fpsBusy=true; const lf=CR.lineOfFire(S.w,w,m)||{from:P(w)}; const eye=new THREE.Vector3(lf.from[0],yOf(...lf.from)+1.55,lf.from[1]);
    const o=CR.odds(S.w,w,m,{reaction:true,doorway}); FP={w,m,eye,t:0,limit:w.role==='sharpshooter'?6.5:5.5,res,mx:.5,my:.5,o,fov:w.role==='sharpshooter'?18:56,yaw:Math.atan2(m.x-eye.x,m.z-eye.z),pitch:0};
    $('fpsWho').textContent=`${w.name} on overwatch`; $('fpsInfo').textContent=`${m.name} · the roll would be ${o.aim}%`; fpsEl.hidden=false; $('stage').classList.add('fp'); if(typeof CUT!=='undefined') CUT.u.uOn.value=0; S.slow=1/7; m.paused=false; }); }
function fpsEnd(r){ if(!FP) return; const f=FP; FP=null; fpsEl.hidden=true; $('stage').classList.remove('fp'); S.slow=1; S.fpsBusy=false; camera.fov=FOV; camera.updateProjectionMatrix(); f.res(r); }
function fpsFire(){ if(!FP) return; const f=FP, sway=(1-f.w.aim/100)*.05+.004, sx=Math.sin(f.t*2.3)*sway, sy=Math.sin(f.t*3.1+1)*sway*.7;
  ndc.set((f.mx*2-1)+sx*6,-(f.my*2-1)+sy*6); ray.setFromCamera(ndc,camera);
  const targets=[]; f.m.fig.root.traverse(o=>{ if(o.isMesh&&!o.userData.ink) targets.push(o); }); const blockers=[]; world.traverse(o=>{ if(o.isMesh&&o.visible&&o.material&&o.material.visible!==false&&o.material!==glassMat) blockers.push(o); });
  const hits=ray.intersectObjects(targets.concat(blockers),false); const first=hits[0];
  if(first&&targets.includes(first.object)){ let head=false; for(let p=first.object;p;p=p.parent) if(p===f.m.fig.head) head=true;
    const W=f.w.weapon, flanked=S.w.coverFrom(P(f.m),P(f.w))===0, crit=head||(flanked&&S.rng()<.5); let dmg=W.dmg[0]+Math.floor(S.rng()*(W.dmg[1]-W.dmg[0]+1))+(crit?W.critDmg:0); const armor=Math.min(f.m.armor||0,dmg); dmg-=armor;
    fpsEnd({hit:true,crit,head,dmg,armor}); }
  else if(first&&first.distance<f.eye.distanceTo(new THREE.Vector3(f.m.x,1,f.m.z))) fpsEnd({hit:false,blocked:true,dmg:0});
  else fpsEnd({hit:false,dmg:0}); }
fpsEl.addEventListener('pointermove',e=>{ if(!FP) return; const r=fpsEl.getBoundingClientRect(); FP.mx=(e.clientX-r.left)/r.width; FP.my=(e.clientY-r.top)/r.height; });
fpsEl.addEventListener('click',()=>fpsFire());
function fpsFrame(dt){ const f=FP; f.t+=dt; if(f.t>f.limit||!f.m.alive){ fpsEnd(null); return; } fpsBar.style.width=Math.max(0,100-f.t/f.limit*100)+'%';
  const ex=f.mx-.5, ey=f.my-.5; if(Math.abs(ex)>.32) f.yaw-=Math.sign(ex)*(Math.abs(ex)-.32)*dt*2.4*f.fov/56; if(Math.abs(ey)>.32) f.pitch=clamp(f.pitch-Math.sign(ey)*(Math.abs(ey)-.32)*dt*1.6*f.fov/56,-.5,.4);
  camera.fov=f.fov; camera.updateProjectionMatrix(); camera.position.copy(f.eye); camera.lookAt(f.eye.x+Math.sin(f.yaw)*Math.cos(f.pitch),f.eye.y+Math.sin(f.pitch),f.eye.z+Math.cos(f.yaw)*Math.cos(f.pitch));
  const sway=(1-f.w.aim/100)*.05+.004, st=$('stage'), W=st.clientWidth, H=st.clientHeight, k=W/(2*Math.tan(f.fov*Math.PI/360))/(W/2);
  fpsX.style.left=(f.mx*W+Math.sin(f.t*2.3)*sway*W*k*1.2)+'px'; fpsX.style.top=(f.my*H+Math.sin(f.t*3.1+1)*sway*.7*H*k*1.2)+'px'; }

// a pipe bomb: an arc, then everyone the blast reaches within 3 m takes damage, cover ignored, armour shredded.
// The interiors physics scatters props, blows doors and glass, and cracks, holes or breaches walls by their build-up.
async function throwBomb(u,p){ if(!p) return; u.kit.pipe--; S.stats.bombs++; u.face=Math.atan2(p[0]-u.x,p[1]-u.z); u.aiming=true;
  arc.geometry.dispose(); arc.geometry=new THREE.BufferGeometry().setFromPoints(arcPoints(P(u),p,24)); arc.computeLineDistances(); arc.visible=true; await wait(450); arc.visible=false; u.aiming=false;
  log(`${u.name} throws a pipe bomb.`); await blast(p,u,CR.V.blastRadius,{grenade:true}); }
async function blast(p,by,r,opt){ const fx=new THREE.Mesh(new THREE.SphereGeometry(1,20,14),new THREE.MeshBasicMaterial({color:0xffa040,transparent:true,opacity:.85,depthWrite:false})); fx.position.set(p[0],yOf(...p)+.4,p[1]); scene.add(fx); blastFx.push({m:fx,t:0}); shake=.45;
  pop(p,opt.charge?'BLAM':'BOOM','crit'); noise(p,60,'blast');
  for(const {u:v,dmg,shred} of CR.blastHits(S.w,p,S.units,r)){ if(v.dead) continue; Motion.kick(v.fig,'hit',1.4,{from:{x:p[0],z:p[1]}}); if(v.down){ v.dead=true; log(`${v.name} is caught in the blast.`); ink(v); continue; }
    if(shred){ v.armor--; pop(v,'SHRED','info'); } pop(v,`−${dmg}`,''); log(`${v.team==='raider'&&!v.vis?'Someone unseen':v.name} takes ${dmg} from the blast${shred?', armour shredded':''}.`); v.hunker=false; harm(v,dmg,by); v.unaware=false; }
  if(opt.grenade){ if(physicsOn()){ grenade({x:p[0],z:p[1]}); await waitSim(); }
    else { const reach=S.w.blastReach(p,r); for(const o of reach.items){ S.w.destroyItem(o); S.destroyed.add(o.it.id); } for(const o of reach.openings){ if(o.e.type==='window'&&o.e.win.state!=='broken') S.w.setWindow(o.e.key,'broken'); else if(/door/.test(o.e.type)&&S.w.doorState(o.e)!=='broken') S.w.setDoor(o.e.key,'broken'); } } }
  rebuild(); S.w.syncMoves(S.rec); S.w.syncWalls(); await wait(300); }
// a breaching charge on a wall: the interiors decide how the build-up gives (block takes one, reinforced concrete two)
async function setCharge(u,edge,at){ if(u.kit.charge<=0) return; u.kit.charge--; const e=edge.e, o=e.key[0], [ax,az,bx,bz]=edge.seg, L2=(bx-ax)**2+(bz-az)**2, a=clamp(((at[0]-ax)*(bx-ax)+(at[1]-az)*(bz-az))/L2,0,1);
  const wx=ax+(bx-ax)*a, wz=az+(bz-az)*a, toward=o==='v'?Math.sign(u.x-wx)||1:Math.sign(u.z-wz)||1, face=typeof aSide==='function'&&toward===aSide(e)?1:2;
  log(`${u.name} sets a charge on the ${e.mat==='stud'?'drywall':e.mat==='frame'?'stucco wall':e.mat==='block'?'block wall':'wall'}.`); await wait(500);
  if(typeof charge==='function'&&physicsOn()){ charge({e,a,x:wx,z:wz,face}); await waitSim(); } else S.w.wallSt[S.w.LV+e.key]={s:3};
  await blast([wx,wz],u,2,{charge:true}); const dm=S.w.wallSt[S.w.LV+e.key]; log(dm&&dm.s>=3?'The wall is breached: a way through.':'The wall is holed: you can see and shoot through.'); }
async function flip(u,o){ const keep=camera.position.clone(); camera.position.set(u.x,camera.position.y,u.z);
  overturn(o.it); camera.position.copy(keep); await wait(50); await waitSim(); await wait(150); S.w.syncMoves(S.rec);
  const mv=S.rec.moved[S.w.LV+o.it.id]; if(mv) log(`${u.name} tips the ${itemName(o.it.key)} over: ${mv.cover} cover.`); else log(`${u.name} cannot get the ${itemName(o.it.key)} over here.`); }
function aid(u,v){ if(!u||u.kit.aid<=0||!v) return; if(v!==u&&Math.hypot(v.x-u.x,v.z-u.z)>1.9){ log(`${u.name} cannot reach ${v.name}.`); return; } u.kit.aid--;
  if(v.down&&!v.stable){ v.stable=true; log(`${u.name} stops ${v.name}'s bleeding.`); pop(v,'stable','info'); }
  else if(v.down&&v.stable){ v.down=false; v.alive=true; v.hp=2; log(`${u.name} gets ${v.name} back on their feet.`); pop(v,'+2','info'); }
  else { v.hp=Math.min(v.max,v.hp+CR.V.aidHeal); log(`${u.name} patches up ${v===u?'themself':v.name}: +${CR.V.aidHeal}.`); pop(v,'+'+CR.V.aidHeal,'info'); }
  ink(v); }
const nearStash=u=>{ const M=S.mission; if(!u||!M||!M.stash||M.stashTaken) return false; const o=S.w.obs.find(x=>x.kind==='item'&&x.it===M.stashItem); return o?boxDist(o.box,u.x,u.z)<1.2:Math.hypot(M.stash[0]-u.x,M.stash[1]-u.z)<1.6; };
function takeStash(u){ const M=S.mission, it=M.stashItem; if(M.stashTaken||!nearStash(u)) return false; M.stashTaken=true; S.rec.taken.push(S.w.LV+it.id); it.searched=true; rebuild();
  log(`${u.name} empties the stash: ${(it.contents||[]).map(c=>c.name+(c.qty>1?' ×'+c.qty:'')).join(', ')||'nothing left'}.`); pop(u,'stash','info'); flash('Stash taken','Now get everyone to the way out (the green ring), or finish the job.',true); drawEvac(); drawHud(); return true; }
function evacuate(u){ const M=S.mission; if(!M.stashTaken||Math.hypot(M.evac[0]-u.x,M.evac[1]-u.z)>M.evacR+.3) return; u.evac=true; u.fig.root.visible=false; M.evacuated.push(u); log(`${u.name} is out.`); }

// ---------- concealment and contact ----------
function spottedCheck(){ for(const r of S.units) if(r.team==='raider'&&r.alive&&r.unaware) for(const u of squad()) if(u.alive&&CR.sees(S.w,r,P(u))){ r.revealT=2; startFight('raider',`${r.vis?r.name:'Someone you had not seen'} saw ${u.name}.`); return true; } return false; }
function contactCheck(){ if(S.prompt) return; for(const r of S.units){ if(r.team!=='raider'||!r.alive||!r.unaware||!r.vis||S.declined.has(r)) continue;
    const u=squad().find(v=>v.alive&&CR.dist(v,r)<CR.V.spot&&CR.lineOfFire(S.w,v,r,{shot:false})); if(!u) continue;
    S.prompt=true; S.slow=.15; for(const v of squad()) if(v.route) v.route=[];
    bannerEl.className='banner ours'; bannerEl.innerHTML=`<b>Contact</b>${u.name} sees ${r.name.toLowerCase()==='sentry'?'the sentry':'a '+r.name.toLowerCase()} ${S.w.insideAt(r.x,r.z)?'inside':'outside'}. They haven't seen you.<br><button type="button" class="pri" data-c="go">Engage: first strike</button><button type="button" data-c="no">Hold back</button>`; bannerEl.hidden=false; clearTimeout(flash.t);
    S.contact=r; drawBar(); clearReach(); return; } }
bannerEl.addEventListener('click',e=>{ const b=e.target.closest('button[data-c]'); if(!b) return; S.prompt=false; S.slow=1; bannerEl.hidden=true; S.busy=false;
  if(b.dataset.c==='go') startFight('squad','The squad opens fire.'); else { S.declined.add(S.contact); log('Holding back. Keep out of their sight lines.'); select(S.sel); } });
function raidersLook(dt){ for(const r of S.units) if(r.team==='raider'&&r.alive&&r.unaware&&r.post!=='sentry'&&!r.patrol){ r.lookT-=dt; if(r.lookT>0) continue; r.look=r.face+(S.rng()-.5)*Math.PI*1.4; r.lookT=3+S.rng()*4; } }
function patrolStep(r,dt){ const pt=r.patrol; if(r.route&&r.route.length) return; if(pt.pause>0){ pt.pause-=dt; if(pt.pause<=0) r.look=r.face+Math.PI*.6; return; }
  const goal=pt.pts[pt.k]; if(Math.hypot(goal[0]-r.x,goal[1]-r.z)<.4){ pt.k=(pt.k+1)%pt.pts.length; pt.pause=2.5; r.look=r.face-Math.PI*.6; return; }
  const F=S.w.field(P(r),200,squad().filter(u=>u.alive).map(P)), path=S.w.pathTo(F,goal); if(!path){ pt.k=(pt.k+1)%pt.pts.length; return; } r.stroll=true; walk(r,path.points); }

// ---------- breaching ----------
async function breach(){ const st=squad().filter(u=>u.alive&&u.stack); if(!st.length) return; S.busy=true; S.phase='breach'; clearReach(); hideHover(); drawSight(); drawEntries(); drawBar(); drawHud();
  flash('Breach',st.map(u=>`${u.name}: ${!S.w.props(u.stack.o).cross?'blows the '+(u.stack.kind==='window'?'boards':'barricade'):u.stack.kind==='window'?'through the window':'kicks the '+(u.stack.role||'side')+' door'}`).join(' · '),true);
  for(const u of st){ const e=u.stack.e, chg=!S.w.props(u.stack.o).cross;
    if(chg){ u.kit.charge--; shake=.35; pop(u.stack.out,'BLAM','crit'); }
    if(/door/.test(e.type)){ if(S.w.doorState(e)!=='broken') S.w.setDoor(e.key,'broken'); } else if(e.type==='window'&&e.win.state!=='broken'){ S.w.setWindow(e.key,'broken'); S.rec.windows[S.w.LV+e.key]=1; }
    u.entryMod=e.type==='window'?-10:0; }
  rebuild(); await wait(250);
  await Promise.all(st.map(u=>{ const e=u.stack, t=e.in; if(!S.w.clearAt(t[0],t[1])||S.units.some(v=>v!==u&&(v.alive||v.down)&&Math.hypot(v.x-t[0],v.z-t[1])<.7)) return Promise.resolve();
    const mid=[(e.o.seg[0]+e.o.seg[2])/2,(e.o.seg[1]+e.o.seg[3])/2]; return walk(u,[{x:u.x,z:u.z},{x:mid[0],z:mid[1],through:e.o},{x:t[0],z:t[1]}]); }));
  st.forEach(u=>u.stack=null);
  S.busy=false; startFight('squad','Breach!',st); }

// ---------- the fight: plan, then go ----------
function startFight(first,why,breachers){ S.round=1; S.prompt=false; S.slow=1; bannerEl.hidden=true; hideHover(); closeMenu();
  for(const u of S.units){ if(u.route&&u.team==='raider') u.route=[]; u.stroll=false; if(u.patrol) u.patrol=null; }
  for(const u of S.units) if(u.team==='squad'&&u.alive){ u.free=false; u.stack=null; u.order=null; }
  S.mission.reinforceIn=3; log(why); S.phase='plan'; drawEntries();
  if(first==='squad'){ const who=breachers||squad().filter(u=>u.alive); for(const u of who) if(u.alive) u.free=true; S.free=true;
    beginPlan(); flash(breachers?'Breach':'First strike',`${breachers?'The breachers':'Everyone'} also get a free shot (+10 aim; anyone unaware has no cover), fired the moment you press Go, before anyone moves. Right click a raider for it.`,true); }
  else { flash('Spotted','They saw you first and scramble for cover.',false); for(const r of S.units) if(r.team==='raider'){ r.unaware=false; r.revealT=2; } inkAll(); raiderPhase(true); } }
function beginPlan(){ S.phase='plan'; S.busy=false; S.mode='move'; for(const u of standing()){ u.order=null; u.ow=false; u.hunker=false; }
  inkAll(); select(standing()[0]); drawOrders(); drawHud(); drawBar(); }
// Go: every soldier carries out their orders at the same moment
async function execute(){ if(!planning()) return; closeMenu(); S.phase='exec'; S.busy=true; S.mode='move'; clearReach(); hideHover(); drawOrders(); drawSight(); drawBar(); drawHud();
  const sq=standing();
  const frees=sq.filter(u=>u.order&&u.order.free); if(frees.length){ await Promise.all(frees.map((u,i)=>wait(i*110).then(()=>fireAt(u,u.order.free.target,u.weapon,{free:true,mod:u.entryMod||0,modLabel:'Through a window'})))); }
  if(S.free){ S.free=false; for(const u of S.units){ u.free=false; u.entryMod=0; if(u.team==='raider') u.unaware=false; } }
  await Promise.all(sq.map((u,i)=>runOrder(u,i)));
  for(const u of sq){ u.order=null; if(u.cooldown&&!u.usedRungun) u.cooldown--; u.usedRungun=false; }
  S.minutes+=CR.V.minutesPerTurn*squad().filter(u=>u.alive||u.down&&!u.dead).length;
  if(dirtyBuild) rebuild(); if(checkEnd()) return; raiderPhase(false); }
async function runOrder(u,i){ const o=u.order; if(!o) return; await wait(i*70); if(!u.alive) return;
  if(o.rungun){ u.cooldown=CR.V.runGunCooldown; u.usedRungun=true; }
  const a=o.act;
  if(a&&a.type==='slash'){ if(!a.target.alive){ log(`${u.name} has nothing to hit: ${a.target.name} is already down.`); pop(u,'no target','info'); S.stats.wasted++; return; }
    const F=S.w.field(P(u),(u.move||CR.V.move)*2,others(u)), spot=CR.meleeSpot(S.w,F,u,a.target,S.units);
    if(!spot){ log(`${u.name} cannot reach ${a.target.name}.`); return; } if(spot.path) await walk(u,spot.path.points); if(u.alive) await fireAt(u,a.target,u.second); return; }
  if(o.move){ u.ow=false; u.hunker=false; await walk(u,o.move.path.points); }
  if(!u.alive||!a) return;
  switch(a.type){
    case 'shoot': await fireAt(u,a.target,u.weapon,{steady:u.role==='sharpshooter'&&!o.move}); break;
    case 'pistol': await fireAt(u,a.target,u.second); break;
    case 'throw': if(u.kit.pipe>0) await throwBomb(u,a.point); break;
    case 'aid': aid(u,a.target); break;
    case 'charge': await setCharge(u,a.edge,a.at); break;
    case 'flip': await flip(u,a.item); break;
    case 'shove': case 'drag': { const it=a.item.it; await waitSim(); const ok=a.type==='shove'?shove(it,null,false):dropAt(it,null,{x:a.point[0],z:a.point[1]}); await waitSim(); S.w.syncMoves(S.rec);
      log(ok?`${u.name} ${a.type==='shove'?'shoves':'drags'} the ${itemName(it.key)} ${a.type==='shove'?'clear':'across'}.`:`${u.name} cannot move the ${itemName(it.key)} there.`); break; }
    case 'close': if(S.w.doorState(a.edge.e)==='open'){ S.w.setDoor(a.edge.e.key,'closed'); rebuild(); log(`${u.name} closes the door.`); } break;
    case 'search': if(!takeStash(u)) log(`${u.name} cannot reach the stash.`); break;
    case 'evac': evacuate(u); break;
    case 'ow': if(u.ammo>0){ u.ow=true; ink(u); log(`${u.name} is on overwatch.`); } break;
    case 'hunker': u.hunker=true; log(`${u.name} hunkers down.`); break;
    case 'reload': u.ammo=u.weapon.ammo; u.reloading=1.4; log(`${u.name} reloads.`); await wait(500); break; } }
// reinforcements: two of the gang from the road, out of the squad's sight, already alert
function reinforce(){ const w=S.w, sq=standing(); const cands=[];
  for(const e of w.entries()){ if(!w.props(e.o).cross) continue; const n=[e.out[0]-e.in[0],e.out[1]-e.in[1]], L=Math.hypot(...n); for(const d of [7,10,13]){ const q=[e.out[0]+n[0]/L*d,e.out[1]+n[1]/L*d]; if(!w.clearAt(...q)||w.insideAt(...q)) continue; if(sq.some(u=>Math.hypot(u.x-q[0],u.z-q[1])<8||w.sight(P(u),q))) continue; cands.push(q); } }
  const picks=[]; for(const q of cands){ if(picks.length>=2) break; if(picks.every(p=>Math.hypot(p[0]-q[0],p[1]-q[1])>1.5)) picks.push(q); }
  picks.forEach((q,i)=>{ const type=i===0?'raider':'brute'; const u=CR.makeUnit(type,{id:'x'+S.units.length,team:'raider',name:CR.ROLES[type].label,x:q[0],z:q[1],ap:0,face:0,unaware:false,vis:false}); u.fig=makeFig(7000+S.units.length*17,i===1,INKS.raider,gunKind(u.weapon)); u.fig.root.visible=false; S.units.push(u); });
  if(picks.length){ log(`Engines on the road: ${picks.length} more raiders arrive.`); flash('Reinforcements',`You hear ${picks.length} more of them come in from the road.`,false); } }
// the raiders' half of the round: every raider decides both its actions, then they all go at once
async function raiderPhase(scramble){ S.phase='raiders'; S.busy=true; clearReach(); hideHover(); drawOrders(); drawSight(); drawBar(); drawHud(); if(!scramble) flash(`Round ${S.round}`,'Raiders',false); await wait(500);
  const M=S.mission; if(!scramble&&M.reinforceIn!=null&&M.reinforceIn>0){ M.reinforceIn--; if(M.reinforceIn===1) log('Engines on the road: more of them are coming.'); if(M.reinforceIn===0) reinforce(); }
  for(const b of CR.morale(S.units,S.rng)){ if(b.vis){ log(`${b.name} breaks and runs.`); pop(b,'RUNS','info'); } ink(b); }
  const rs=S.units.filter(u=>u.team==='raider'&&u.alive), field=S.units.filter(u=>!u.evac);
  for(const r of rs){ r.hunker=false; r.ow=false; }
  const plans=rs.map(r=>CR.planAI(S.w,r,field,S.rng,{scramble}));
  await Promise.all(rs.map((r,i)=>runAI(r,plans[i],i)));
  if(checkEnd()) return;
  S.minutes+=CR.V.minutesPerTurn*rs.length; S.round++;
  for(const u of squad()){ if(u.down&&!u.stable&&!u.dead){ u.bleed--; if(u.bleed<=0){ u.dead=true; log(`${u.name} bled out.`); } else log(`${u.name} is bleeding out: ${u.bleed} turn${u.bleed>1?'s':''} left.`); ink(u); } }
  if(checkEnd()) return;
  flash(`Round ${S.round}`,'Give your orders, then Go.',true); beginPlan(); }
async function runAI(r,plan,i){ await wait(i*90);
  for(const a of plan){ if(!r.alive) return;
    if(a.type==='shoot') await fireAt(r,a.target,r.weapon);
    else if(a.type==='melee'){ if(a.path) await walk(r,a.path.points); if(r.alive) await fireAt(r,a.target,r.weapon); }
    else if(a.type==='reload'){ r.ammo=r.weapon.ammo; r.reloading=1.4; if(r.vis) log(`${r.name} reloads.`); await wait(500); }
    else if(a.type==='escape'){ r.alive=false; r.fled=true; r.fig.root.visible=false; log(`${r.vis?r.name:'Someone'} gets away.`); return; }
    else if(a.type==='move'&&a.path){ await walk(r,a.path.points); if(dirtyBuild) rebuild(); }
    else if(a.type==='overwatch'){ r.ow=true; ink(r); } } }
function checkEnd(){ const M=S.mission, inside=standing(), r=S.units.some(u=>u.team==='raider'&&u.alive);
  const away=M.stashTaken&&M.evacuated.length&&!inside.length&&!squad().some(u=>u.down&&!u.dead&&!u.evac);
  if(r&&inside.length&&!away) return false; if(!r&&S.phase==='explore') return false;
  S.phase='over'; S.busy=false; S.prompt=false; S.slow=1; clearReach(); hideHover(); drawSight(); drawEvac(); drawOrders();
  for(const t of S.units) if(t.team==='raider'&&!t.fled){ t.vis=true; t.fig.root.visible=true; }
  const won=!r||away, mins=S.minutes-14*60, rs=S.units.filter(u=>u.team==='raider'), sq=squad();
  const notes=[]; sq.forEach((u,i)=>{ const m=u.member; m.missions++; m.kills+=u.kills||0;
    if(u.dead){ S.roster.memorial.push({name:m.name,nick:m.nick,role:m.role,rank:rankName(m.xp),kills:m.kills,fell:S.G.label}); notes.push(`${m.name} is remembered.`);
      S.roster.squad[i]={name:FIRST[(S.roster.next++)%FIRST.length],role:m.role,xp:0,kills:0,missions:0,seed:S.roster.next*13}; return; }
    const before=CR.rankOf(m.xp); m.xp+=(u.kills||0)+(won?1:0); const after=CR.rankOf(m.xp);
    if(after>before){ if(!m.nick){ const ns=NICK[m.role]; m.nick=ns[(m.name.length+m.kills)%ns.length]; } notes.push(`${m.name} “${m.nick}” makes ${CR.RANKS[after]}.`); } });
  saveRoster();
  const line=`${rs.filter(u=>u.dead).length} killed, ${rs.filter(u=>u.fled).length} fled · squad: ${sq.filter(u=>u.alive&&!u.evac).length} standing, ${M.evacuated.length} out, ${sq.filter(u=>u.down&&!u.dead).length} down, ${sq.filter(u=>u.dead).length} dead · ${S.stats.hits}/${S.stats.shots} hits${S.stats.wasted?`, ${S.stats.wasted} wasted on the already down`:''}${S.stats.bombs?`, ${S.stats.bombs} pipe bomb${S.stats.bombs>1?'s':''}`:''}${M.stashTaken?' · stash taken':''} · ${Math.floor(mins/60)} h ${mins%60} min of daylight`;
  flash(!won?'Squad lost':away&&r?'Away with the stash':'Building clear',(!won?'Nobody is left standing. ':'')+line+(notes.length?'<br>'+notes.join(' '):''),won,true);
  log(line); notes.forEach(log); inkAll(); drawBar(); drawHud(); return true; }

// ---------- input ----------
$('bar').addEventListener('click',e=>{ const b=e.target.closest('button'); if(!b||b.disabled) return;
  if(b.dataset.i!==undefined){ const u=S.units[+b.dataset.i]; if(u.alive&&!S.busy) select(u); return; }
  act(b.dataset.a); });
async function act(a){ const u=S.sel;
  if(a==='restart'){ setup(); return; } if(a==='reroll'){ S.seed++; setup(); return; }
  if(a==='go'){ execute(); return; }
  if(!u||S.busy) return;
  if(a==='clear'){ u.order=null; afterOrder(u); return; }
  if(a==='back'){ S.mode='move'; arc.visible=false; hideHover(); drawReach(); drawBar(); return; }
  if(a==='stack'){ if(u.stack){ u.stack=null; drawBar(); return; } const e=entryAt(u); if(!e) return; S.busy=true; clearReach(); await walk(u,[{x:u.x,z:u.z},{x:e.out[0],z:e.out[1]}]); if(S.phase!=='explore') return; S.busy=false; u.stack=e;
    u.face=Math.atan2(e.in[0]-e.out[0],e.in[1]-e.out[1]); drawReach(); drawBar(); return; }
  if(a==='breach'){ breach(); return; }
  if(a==='fire'){ startFight('squad','The squad opens fire.'); return; }
  if(a==='search'){ takeStash(u); drawBar(); return; }
  if(a==='wait'){ S.minutes+=1; raidersLook(4); drawHud(); return; } }
const held=new Set();
addEventListener('keyup',e=>held.delete(e.key.toLowerCase())); addEventListener('blur',()=>held.clear());
addEventListener('keydown',e=>{ if(e.target.tagName==='SELECT') return; const k=e.key;
  if(!FP&&/^[wasd]$/i.test(k)&&!e.ctrlKey&&!e.metaKey){ held.add(k.toLowerCase()); return; }
  if(FP){ if(k==='Escape') fpsEnd(null); if(k===' '){ e.preventDefault(); fpsFire(); } return; }
  if(k==='Escape'){ if(!ctxEl.hidden){ closeMenu(); return; } act('back'); return; }
  if(k==='q'||k==='Q') view.az-=Math.PI/2; else if(k==='e'||k==='E') view.az+=Math.PI/2;
  if(S.busy||S.prompt) return; const u=S.sel;
  if(k===' '&&S.phase==='plan'){ e.preventDefault(); execute(); return; }
  if(k==='b'||k==='B') act('breach');
  if(S.phase==='plan'&&u){ if(k==='2'&&u.ammo>0){ setAct(u,{type:'ow'}); afterOrder(u); } else if(k==='3'){ setAct(u,{type:'hunker'}); afterOrder(u); } else if(k==='4'&&u.ammo<u.weapon.ammo){ setAct(u,{type:'reload'}); afterOrder(u); } else if(k==='Backspace'){ e.preventDefault(); act('clear'); } }
  if(k==='Tab'){ e.preventDefault(); const sq=standing(); select(sq[(sq.indexOf(S.sel)+1)%sq.length]); } });
const canvas3=renderer.domElement, ray=new THREE.Raycaster(), ndc=new THREE.Vector2(), plane=new THREE.Plane(new THREE.Vector3(0,1,0),-.08), hitP=new THREE.Vector3();
function pointUnder(ev){ const r=canvas3.getBoundingClientRect(); ndc.set((ev.clientX-r.left)/r.width*2-1,-(ev.clientY-r.top)/r.height*2+1); ray.setFromCamera(ndc,camera); return ray.ray.intersectPlane(plane,hitP)?[hitP.x,hitP.z]:null; }
// the unit under the pointer, picked on screen along its figure (feet to head), not on the ground behind it
function pickUnit(ev,filter){ const r=canvas3.getBoundingClientRect(), mx=ev.clientX-r.left, my=ev.clientY-r.top; let best=null;
  for(const u of S.units){ if(u.fled||u.evac||!u.fig.root.visible||(filter&&!filter(u))) continue; const y0=yOf(u.x,u.z), standing=u.alive&&!u.down;
    const a=screenOf(u.x,y0+(standing?.1:.05),u.z), b=screenOf(u.x,y0+(standing?1.75:.4),u.z); if(!a||!b) continue;
    const hgt=Math.hypot(b[0]-a[0],b[1]-a[1]), wid=Math.max(14,hgt*.22), q=SP.ptSeg(mx,my,a[0],a[1],b[0],b[1]);
    if(q.d<=wid&&(!best||q.d<best.d)) best={u,d:q.d}; }
  return best&&best.u; }
function target(p){ if(!p||!S.F) return null; const q=S.w.snap(p), ct=S.w.costTo(S.F,q); if(ct&&!ct.over) return {p:q,cost:ct.cost,snapped:q!==p};
  const c2=S.w.costTo(S.F,p); return c2&&!c2.over?{p,cost:c2.cost,snapped:false}:null; }
function landing(u,p){ if(!p) return null; const d=Math.hypot(p[0]-u.x,p[1]-u.z); let q=p; if(d>CR.V.throwRange){ q=[u.x+(p[0]-u.x)/d*CR.V.throwRange,u.z+(p[1]-u.z)/d*CR.V.throwRange]; }
  const from=[[u.x,u.z],...S.w.leans([u.x,u.z],q)]; return from.some(f=>S.w.sight(f,q,{shot:true}))?q:null; }
let drag=null;
canvas3.addEventListener('pointerdown',e=>{ drag={x:e.clientX,y:e.clientY,btn:e.button,pan:e.button===2||e.shiftKey,moved:0}; canvas3.setPointerCapture(e.pointerId); });
canvas3.addEventListener('pointermove',e=>{ if(!drag){ const fp=S.w&&pointUnder(e); if(fp&&S.w.insideAt(...fp)){ cutAt=fp; cutT=performance.now(); } const h=S.w&&!FP?pickUnit(e,v=>v.team==='squad'||v.vis):null; canvas3.style.cursor=h?'pointer':'';
    if(h&&h.team==='raider'&&h.alive&&ctxEl.hidden){ hideHover(); hoverEl.textContent=`${h.name} · ${h.hp}/${h.max} HP${h.armor?' · armour '+h.armor:''}${planning()?'\nClick or right click: what '+(S.sel?S.sel.name:'your soldier')+' can do to them':S.phase==='explore'?'\nRight click: engage':''}`; hoverEl.style.whiteSpace='pre-line'; return; }
    hover(pointUnder(e)); return; } const dx=e.clientX-drag.x, dy=e.clientY-drag.y; drag.x=e.clientX; drag.y=e.clientY; drag.moved+=Math.abs(dx)+Math.abs(dy);
  if(drag.moved<(drag.btn===2?12:6)) return; S.camGoal=null; S.camHold=performance.now()+5000; closeMenu();
  if(drag.pan){ const s=view.dist*.0011, ca=Math.cos(view.az), sa=Math.sin(view.az); view.target.x-=(dx*ca-dy*sa)*s; view.target.z-=(-dx*sa-dy*ca)*s; }
  else { view.az-=dx*.008; view.el=clamp(view.el+dy*.006,.32,1.2); } });
canvas3.addEventListener('pointerup',e=>{ const click=drag&&drag.moved<(drag.btn===2?12:6), btn=drag&&drag.btn; drag=null; if(!click||S.prompt) return; const p=pointUnder(e);
  const hit=pickUnit(e,v=>v.team==='squad'||v.vis);
  if(btn===2){ rightClick(e,p,hit||null); return; }
  closeMenu();
  if(S.mode==='drag'&&S.sel&&p){ setAct(S.sel,{type:'drag',item:S.dragItem,point:p}); S.mode='move'; S.dragItem=null; afterOrder(S.sel); return; }
  if(S.mode==='throw'&&S.sel){ const q=landing(ghostAt(S.sel),p); if(q){ setAct(S.sel,{type:'throw',point:q}); S.mode='move'; afterOrder(S.sel); } else log('No clear throw there.'); return; }
  if(hit&&hit.team==='raider'&&planning()){ rightClick(e,p,hit); return; }   // a left click on a raider opens the same options
  if(!p) return;
  const u=hit&&hit.team==='squad'&&hit.alive&&!hit.evac?hit:S.units.find(v=>v.alive&&!v.evac&&v.team==='squad'&&S.phase==='plan'&&Math.hypot(planned(v)[0]-p[0],planned(v)[1]-p[1])<.55); if(u&&!S.busy){ select(u); return; }
  if(S.busy||!S.sel) return; const t=target(p);
  if(S.phase==='explore'){ if(t) walkTo(S.sel,t.p); return; }
  if(S.phase==='plan'){ if(!t){ log('Out of reach this round.'); return; } const sel=S.sel, mv=sel.move||CR.V.move;
    if(t.cost>2*mv||(t.cost>moveBudget(sel)&&!(sel.order&&sel.order.act))){ log('Out of reach this round.'); return; }
    if(standing().some(v=>v!==sel&&Math.hypot(planned(v)[0]-t.p[0],planned(v)[1]-t.p[1])<.7)){ log('Someone is already going there.'); return; }
    setMove(sel,t.p,t.cost,S.w.pathTo(S.F,t.p)); afterOrder(sel); } });
canvas3.addEventListener('contextmenu',e=>e.preventDefault());
canvas3.addEventListener('wheel',e=>{ e.preventDefault(); view.dist=clamp(view.dist*Math.exp(e.deltaY*.0012),8,90); },{passive:false});
function hideHover(){ ghost.visible=false; route.visible=false; hoverSpot=null; while(glyphs.children.length) glyphs.children.pop(); hoverEl.textContent=''; for(const m of ribbons.children.filter(m=>m.userData.blast)){ ribbons.remove(m); m.geometry.dispose(); } }
function hover(p){ if(S.mode==='throw'){ hoverThrow(p); return; } hideHover(); if(!p||!S.w||S.phase==='over'||S.busy||S.prompt||!ctxEl.hidden||!(S.phase==='plan'||S.phase==='explore')) return; const w=S.w, t=target(p);
  const parts=[];
  if(!t){ const it=w.obs.find(o=>o.kind==='item'&&!o.destroyed&&!o.flat&&p[0]>=o.box.x0&&p[0]<=o.box.x1&&p[1]>=o.box.z0&&p[1]<=o.box.z1); if(it) parts.push(`${itemName(it.it.key)}: ${it.cover||it.it.spec.cover} cover${typeof FLIP_PROPS!=='undefined'&&FLIP_PROPS.has(it.it.key)&&!it.mv?' · right click to overturn':''}`); else if(S.F&&S.phase==='plan') parts.push('Out of reach'); hoverEl.textContent=parts.join('\n'); return; }
  ghost.position.set(t.p[0],yOf(...t.p)+.05,t.p[1]); ghost.visible=true; hoverSpot=S.phase==='plan'?t.p:null;
  const path=w.pathTo(S.F,t.p); if(path){ route.geometry.dispose(); route.geometry=new THREE.BufferGeometry().setFromPoints(path.points.map(q=>new THREE.Vector3(q.x,yOf(q.x,q.z)+.1,q.z))); route.computeLineDistances(); route.visible=true; }
  const fs=S.units.filter(r=>r.team==='raider'&&r.alive&&r.vis), cv=fs.map(r=>w.coverFrom(t.p,P(r)));
  fs.forEach((r,i)=>{ const a=Math.atan2(r.x-t.p[0],r.z-t.p[1]), h=cv[i]===2?1:cv[i]===1?.5:.06, m=new THREE.Mesh(glyphG,glyphM[cv[i]]); m.scale.set(.32,h,.05); m.rotation.y=a; m.position.set(t.p[0]+Math.sin(a)*.62,yOf(...t.p)+h/2,t.p[1]+Math.cos(a)*.62); m.renderOrder=7; glyphs.add(m); });
  if(fs.length) parts.push(`Cover vs ${fs.length} in sight: ${cv.filter(v=>v===2).length} full · ${cv.filter(v=>v===1).length} half · flanked by ${cv.filter(v=>v===0).length}`);
  if(S.phase==='plan') parts.push(`${t.cost.toFixed(1)} effective m · ${t.cost<=(S.sel.move||CR.V.move)?'1 action':'dash, 2 actions'}${t.snapped?' · into cover':''}`);
  else { const e=w.entries().find(x=>Math.hypot(x.out[0]-t.p[0],x.out[1]-t.p[1])<1.1); if(e) parts.push(`${e.kind==='window'?'Window':(e.role||'side')+' door'}: ${usable(e,S.sel)?'right click to stack here':'only a Breacher\'s charge gets through'}`); }
  hoverEl.textContent=parts.join('\n'); hoverEl.style.whiteSpace='pre-line'; }
function hoverThrow(p){ ghost.visible=false; route.visible=false; while(glyphs.children.length) glyphs.children.pop(); for(const m of ribbons.children.filter(m=>m.userData.blast)){ ribbons.remove(m); m.geometry.dispose(); } arc.visible=false;
  const u=S.sel; if(!u||!p){ hoverEl.textContent=''; return; } const g=ghostAt(u), q=landing(g,p); if(!q){ hoverEl.textContent='No clear throw there'; return; }
  const m=ribbonMesh(ring(q,CR.V.blastRadius),ribbonM.blast,.18); m.userData.blast=true; ribbons.add(m);
  arc.geometry.dispose(); arc.geometry=new THREE.BufferGeometry().setFromPoints(arcPoints(planned(u),q,24)); arc.computeLineDistances(); arc.visible=true;
  const hits=CR.blastHits(S.w,q,S.units).filter(h=>!h.u.dead&&(h.u.team==='squad'||h.u.vis));
  hoverEl.textContent=`Pipe bomb: ${hits.filter(h=>h.u.team==='raider').map(h=>h.u.name+' −'+h.dmg+(h.shred?' (shred)':'')).join(', ')||'nobody you can see'}${hits.some(h=>h.u.team==='squad')?' · hits your own: '+hits.filter(h=>h.u.team==='squad').map(h=>h.u.name).join(', '):''}\nIgnores cover · scatters props · can hole thin walls`; hoverEl.style.whiteSpace='pre-line'; }

// ---------- per frame ----------
let last=performance.now(), detT=0, visT=0, cutAt=null, cutT=0;
function resize(){ const st=$('stage'), w=st.clientWidth, h=st.clientHeight; renderer.setSize(w,h,false); camera.aspect=w/Math.max(1,h); camera.updateProjectionMatrix(); }
new ResizeObserver(resize).observe($('stage'));
const motionState=(u,act)=>({act,mood:u.fleeing?'panicked':u.alive&&u.hp<=u.max/2?'wounded':'calm',ground:(x,z)=>yOf(x,z)});
function frame(now){ requestAnimationFrame(frame); const real=Math.min(.05,(now-last)/1000)*S.timeScale; last=now; if(!S.w) return;
  const dt=real*S.slow;
  for(const m of glowMats) m.uniforms.t.value=now/1000;
  for(let i=waits.length-1;i>=0;i--){ waits[i].t-=real*1000; if(waits[i].t<=0){ waits[i].r(); waits.splice(i,1); } }
  const st=$('stage'), W=st.clientWidth, H=st.clientHeight;
  for(const p of pops){ p.t+=real; tmpV.set(p.x,p.y+p.t*1.1,p.z).project(camera); p.el.style.left=((tmpV.x+1)/2*W)+'px'; p.el.style.top=((1-tmpV.y)/2*H)+'px'; p.el.style.opacity=String(Math.max(0,1-p.t/1.6)); }
  for(let i=pops.length-1;i>=0;i--) if(pops[i].t>1.6){ pops[i].el.remove(); pops.splice(i,1); }
  for(const t of tracers) t.t+=real; for(let i=tracers.length-1;i>=0;i--){ const t=tracers[i]; t.l.material.opacity=Math.max(0,1-t.t/.35); if(t.t>.35){ scene.remove(t.l); t.l.geometry.dispose(); tracers.splice(i,1); } }
  for(const b of blastFx){ b.t+=real; b.m.scale.setScalar(.5+b.t*9); b.m.material.opacity=Math.max(0,.85-b.t*2.4); } for(let i=blastFx.length-1;i>=0;i--) if(blastFx[i].t>.4){ scene.remove(blastFx[i].m); blastFx[i].m.geometry.dispose(); blastFx.splice(i,1); }
  if((visT+=real)>.15){ const before=S.units.filter(u=>u.vis).length; updateVision(visT); visT=0; if(S.units.filter(u=>u.vis).length!==before){ drawBar(); drawHud(); if(S.phase==='explore') drawSight(); } }
  if(S.phase==='explore'&&!S.prompt){ raidersLook(dt); for(const r of S.units) if(r.patrol&&r.alive&&r.unaware) patrolStep(r,dt);
    if((detT+=real)>.2){ detT=0; if(!spottedCheck()) contactCheck(); } }
  const acting=[];
  for(const u of S.units){ const f=u.fig; if(u.fled||u.evac) continue;
    let moving=false;
    if(Motion.busy(f)&&u.alive){ u.x=f.root.position.x; u.z=f.root.position.z; moving=true; }   // a vault through a window: the clip moves the body
    else if(u.route&&!u.paused){ if(!u.route.length||(!u.alive&&!u.evac)){ u.route=null; const r=u.done; u.done=null; r&&r(); }
      else { const q=u.route[0], dx=q.x-u.x, dz=q.z-u.z, d=Math.hypot(dx,dz), sp=(u.stroll?1.4:S.phase==='explore'?2.2:3.6)*dt; moving=true;
        if(q.through&&!q.opened&&d<.75){ q.opened=true; opening(u,q.through);
          // a window: climb through it with the motion module's vault
          if(q.through.e&&q.through.e.type==='window'&&f.root.visible&&!Motion.reduce&&d>.3){ const mid=[(q.through.seg[0]+q.through.seg[2])/2,(q.through.seg[1]+q.through.seg[3])/2], yaw=Math.atan2(dx,dz);
            const dur=Motion.traverse(f,{type:'vault',x:mid[0]-Math.sin(yaw)*.12,z:mid[1]-Math.cos(yaw)*.12,yaw,height:Math.max(.4,S.w.FY+(q.through.e.win.sill||.9)-yOf(u.x,u.z)),depth:.25},motionState(u,'ready')); if(dur){ u.face=yaw; u.route.shift(); acting.push(u); continue; } } }
        const step=Math.min(d,sp); if(d>1e-6){ u.x+=dx/d*step; u.z+=dz/d*step; u.face=Math.atan2(dx,dz); } u.trav+=step; if(d<=sp) u.route.shift();
        if(u.trav>=.3){ u.trav=0; if(S.phase==='exec'||S.phase==='raiders') overwatchCheck(u); } } }
    if(moving||u.aiming) acting.push(u);
    if(u.team==='raider'&&u.unaware&&u.alive&&S.phase==='explore'&&!(u.route&&u.route.length)){ let a=u.look-u.face; a=Math.atan2(Math.sin(a),Math.cos(a)); u.face+=a*Math.min(1,dt*1.5); }
    if(u.reloading) u.reloading=Math.max(0,u.reloading-dt);
    if(!Motion.busy(f)){ f.root.position.set(u.x,yOf(u.x,u.z),u.z); let a=u.face-f.root.rotation.y; a=Math.atan2(Math.sin(a),Math.cos(a)); f.root.rotation.y+=a*Math.min(1,dt*9); }
    const concealed=S.phase==='explore'&&u.team==='squad';
    const act=u.dead||(!u.alive&&!u.down)?'dead':u.down?'fall':u.reloading?'reload':u.aiming?'shoot':u.hunker||(concealed&&u.stack)?'hunker':u.ow?'aim':concealed?(moving?'crouch-walk':'crouch'):S.phase!=='explore'||u.team==='squad'?'ready':'idle';
    Motion.update(f,motionState(u,act),dt); }
  if(S.phase==='explore'&&S.sight&&(frame.t=(frame.t||0)+real)>.25){ frame.t=0; drawSight(); }
  if(FP){ fpsFrame(real); renderer.render(scene,camera); return; }
  // while orders play out, the camera follows whoever is moving or shooting (the middle of them)
  if((S.phase==='exec'||S.phase==='raiders'||S.phase==='breach')&&now>S.camHold){ const vis=acting.filter(u=>u.team==='squad'||u.vis); if(vis.length){ let x=0,z=0; for(const u of vis){ x+=u.x; z+=u.z; } S.camGoal={x:x/vis.length,z:z/vis.length}; } }
  if(S.camGoal&&now>S.camHold){ view.target.x+=(S.camGoal.x-view.target.x)*Math.min(1,real*2.2); view.target.z+=(S.camGoal.z-view.target.z)*Math.min(1,real*2.2); if(S.sel&&(S.phase==='plan'||S.phase==='explore')&&!S.busy&&S.sel.alive) S.camGoal={x:S.sel.x,z:S.sel.z}; }
  // WASD moves the camera over the ground, relative to the way it faces
  if(held.size&&!FP){ const f=(held.has('w')?1:0)-(held.has('s')?1:0), rt=(held.has('d')?1:0)-(held.has('a')?1:0), sp=view.dist*.9*real, sa=Math.sin(view.az), ca=Math.cos(view.az);
    if(f||rt){ view.target.x+=(-sa*f+ca*rt)*sp; view.target.z+=(-ca*f-sa*rt)*sp; S.camGoal=null; S.camHold=now+5000; } }
  // the interiors' section cutaway: walls between the camera and the focus drop to a stub. The focus is the floor under
  // the pointer while it moves over the building, otherwise whoever the camera is following.
  if(typeof CUT!=='undefined'&&typeof stepCut==='function'){ const p=cutAt&&now-cutT<2500?cutAt:[view.target.x,view.target.z]; CUT.goal.set(p[0],0,p[1]); }
  placeCamera(); if(shake>0){ shake=Math.max(0,shake-real); const k=shake*.35; camera.position.x+=(Math.random()-.5)*k; camera.position.y+=(Math.random()-.5)*k; } applyView(); if(typeof stepCut==='function') stepCut(); drawBadges(); renderer.render(scene,camera); }

// ---------- header ----------
$('bSel').onchange=()=>{ S.seed=0; setup(); }; $('hSel').onchange=()=>setup();
$('rerollBtn').onclick=()=>{ S.seed++; setup(); }; $('restartBtn').onclick=()=>setup();
$('labelsBtn').onclick=()=>{ S.labels=!S.labels; $('labelsBtn').setAttribute('aria-pressed',S.labels); };
$('sightBtn').onclick=()=>{ S.sight=!S.sight; $('sightBtn').setAttribute('aria-pressed',S.sight); drawSight(); };
$('fpsBtn').onclick=()=>{ S.fps=!S.fps; $('fpsBtn').setAttribute('aria-pressed',S.fps); };
$('rosterBtn').onclick=()=>{ const mem=S.roster.memorial; S.roster=freshRoster(); S.roster.memorial=mem; saveRoster(); setup(); log('A fresh squad. The memorial keeps '+mem.length+' name'+(mem.length===1?'':'s')+'.'); };
const MODES=['cutaway','low','shell'], ML={cutaway:'Walls: cutaway',low:'Walls: low',shell:'Walls: full + roof'};
$('wallsBtn').onclick=()=>{ view.mode=MODES[(MODES.indexOf(view.mode)+1)%MODES.length]; $('wallsBtn').textContent=ML[view.mode]; };
resize(); setup(); requestAnimationFrame(frame);
window.__combat={S,CR,select,act,breach,startFight,setup,entryAt,target,usable,landing,throwBomb,aid,setMove,setAct,execute,rightClick,previewOdds,orderOf,planned,standBeside,fpsShot,fpsFire,fpsEnd,get FP(){ return FP; },reinforce,nearStash,closeMenu,beginPlan,updateVision};
})();
